### ISSUE TITLE
Système de ticket

### ISSUE THREAD

**Issue by Mrcoco29** [MrTigreroux/TigerReports#1]
Salut,

J'aimerais savoir si il serait possible de légèrement modifier le plugin, pour que en plus de gérer les signalements de joueurs, il puisse faire un système de ticket support. 

Je pensais pouvoir bidouiller la chose, pour que cela puisse me convenir, en créant un alias /ticket (par exemple) qui ferait /report ticket <message du joueur>.  Comme ça, les administrateurs/modérateurs auraient pu voir le signalement d'un joueur "ticket" avec le message. Le seul problème, est que les joueurs ne peuvent pas voir les commentaires des signalements (à ma connaissance :3). Il serait donc top de leur permettre de les voir ou de créer un système dédié pour les tickets.

Si ma demande n'est pas clair, je pourrais reformuler.

Bonne fin de journée, Mr_coco29

**Comment by MrTigreroux** [comment]
Vous pouvez désormais (avec la version 1.3 ou supérieure) envoyer les commentaires de votre choix au signaleur en faisant un clic droit. Vous pouvez annuler cet envoi en re-faisant un clic droit. Si le signaleur n'est pas connecté au moment de l'envoi, il sera informé du commentaire à sa prochaine connexion.
Il est conseillé de supprimer votre fichier messages.yml (ou de copier/coller les nouveaux messages recensés sur la page spigot du plugin) afin que les nouveaux messages soient intégrés et que vous puissiez donc les modifier, sinon ce seront les messages par défaut qui seront affichés.

Je n'ai malheureusement pas créé de plugin dédié aux tickets étant donné que je n'en vois personnellement pas vraiment l'intérêt. Selon moi, un mail ou bien un message privé directement sur le serveur suffirait en cas de problème de la part d'un joueur.
Toute fois, je peux comprendre que cette fonctionnalité soit assez intéressante, c'est pourquoi j'ai tout de même ajouté à TigerReports la possibilité d'envoyer les commentaires au signaleur comme indiqué plus haut.

Merci pour votre suggestion et bonne journée.

**Comment by Mrcoco29** [comment]
Super, merci !

J'affectionne aussi beaucoup les emails, c'est pourquoi j'insiste lourdement auprès de mes joueurs afin d'utiliser en priorité cette solution. 
Toutefois, je sais que certains joueurs ne souhaitent pas passer par un système extérieur au jeu, et le système de MP ne me convient pas car il ne me permet pas d'assigner aux membres de mon équipe chaque problème efficacement.

Merci encore, pour cette modification rapide, ainsi que votre réponse positive à ma demande.

Bonne journée !
