### ISSUE TITLE
[Suggestion] Disable Certain Features

### ISSUE THREAD

**Issue by SkylixMC** [MrTigreroux/TigerReports#10]
I would like to suggest adding a feature where you are able to disable certain parts of the plugin.

For example, I would like to disable the punishment GUI because I use another plugin to manage bans. I think it would be very helpful to be able to disable this feature and help me customize tigerreports better to meet my server's needs.

**Comment by MrTigreroux** [comment]
Ok, I will add this option in the next version.
What other feature would you like to be able to disable ?

**Comment by MrTigreroux** [comment]
This option has been added in the [version 4.8](https://www.spigotmc.org/resources/tigerreports.25773/update?update=293126) with `Config: Punishments: Enabled` setting in config.yml file.
Thank you for suggesting it, if you have other suggestions they are welcome.
