### ISSUE TITLE
unkown command

### ISSUE THREAD

**Issue by bosszepro** [MrTigreroux/TigerReports#104]
Hello, when I enable tiggerreport on my server, I can do /report (nickname) and, when i click on an item in the GUI it say unkown command. 0 error log in console. Can anyone know that ?

**Comment by MrTigreroux** [comment]
The command executed is `/tigerreports:report`, probably you use a plugin which blocks commands with a `:`, then configure that plugin to allow the command of TigerReports.

**Comment by bosszepro** [comment]
Ok, thank you !
So I have a secod question : How can I know which plugin is blocking the :
