### ISSUE TITLE
Cannot see reports in the /reports menu.

### ISSUE THREAD

**Issue by Peps3k** [MrTigreroux/TigerReports#109]
Also when I use **/reports** it sends an error message to the console:

![image](https://user-images.githubusercontent.com/77855606/167252153-82e1d2f7-04f7-4042-9815-94cdc74e0233.png)

**Comment by MrTigreroux** [comment]
You need to update your MySQL database: change the type of the column "archived" in "tigerreports_reports" table to `INT(1)`.
If you don't know how to do so, you can follow the instructions [here](https://github.com/MrTigreroux/TigerReports/wiki/Change-type-of-'reporter_uuid'-(or-'reason')-column).

**Comment by Peps3k** [comment]
Thank you. It works now. ;)
