### ISSUE TITLE
Error with /reports

### ISSUE THREAD

**Issue by SiriHackYT** [MrTigreroux/TigerReports#110]
![MobaXterm_d2GIY22C5I](https://user-images.githubusercontent.com/49961233/167256270-7b7ec2e7-9c87-4509-959a-2742f0952685.png)

All it's on the screen

**Comment by MrTigreroux** [comment]
This error should be fixed in the new [version 5.0.9](https://www.spigotmc.org/resources/tigerreports.25773/update?update=455376). Thank you for reporting it.
Please let me know if it is still there or if you encounter other errors.
