### ISSUE TITLE
Error with /reports (Boolean cannot be cast to int)

### ISSUE THREAD

**Issue by SiriHackYT** [MrTigreroux/TigerReports#111]
![MobaXterm_GBOJMnMDcu](https://user-images.githubusercontent.com/49961233/167264953-b09b5a81-cf57-45a4-9d4c-cb6e33fcf396.png)
I think i need to switch a column to Int(1) but can i make this on my actual DB with version 4 ?

**Comment by MrTigreroux** [comment]
Yes you need to change "archived" column of "tigerreports_reports" table to `INT(1)`. Follow the instructions [here](https://github.com/MrTigreroux/TigerReports/wiki/Change-type-of-'reporter_uuid'-(or-'reason')-column) if you don't know how to do so.

**Comment by SiriHackYT** [comment]
And this can create problem with old reports in mySQL?

**Comment by MrTigreroux** [comment]
No it shouldn't, the previous type of "archived" is TINYINT(1) which is an integer but considered by some SQL implementations as a boolean.

**Comment by SiriHackYT** [comment]
I have this error now 
![image](https://user-images.githubusercontent.com/49961233/167271247-f9b56b45-b4e1-4562-b882-cc4fa1a6d518.png)

**Comment by MrTigreroux** [comment]
Thank you for reporting it, it should be fixed in the new [version 5.0.11](https://www.spigotmc.org/resources/tigerreports.25773/update?update=455533).
