### ISSUE TITLE
Hex in display names

### ISSUE THREAD

**Issue by kforbro** [MrTigreroux/TigerReports#112]
hex codes are not parsed correctly in some chat messages. The prefix in the chat should have been red, it is displayed correctly in the GUI
prefix: `&x&b&4&1&2&1&7&lᴏ&x&b&5&1&3&1&8&lᴡ&x&b&7&1&4&1&9&lɴ&x&b&8&1&5&1&a&lᴇ&x&b&a&1&6&1&b&lʀ&7 `
![image](https://user-images.githubusercontent.com/39985355/167503882-23c7343c-6ff7-478a-a9cc-f1887110ccd4.png)

**Comment by kforbro** [comment]
> It works fine for me:
> 
> ![](https://camo.githubusercontent.com/1bec99bf23fcda3081284d202069b2e63b956fc4c65418c146ff5d66ba74b1ec/68747470733a2f2f692e696d6775722e636f6d2f63676c595643782e706e67)
> 
> Have you tried to restart your server ? What version of Spigot do you use ? What version of TigerReports do your use ? What version of Vault do you use ? What plugin do you use to set prefix ? Could you copy/paste the section "VaultChat" of your plugins/TigerReports/config.yml file please ? Could you copy/paste the concerned messages configured in your plugins/TigerReports/messages.yml file please ?

It doesn't work right for you either. The prefix should be a red gradient. This format is supported in 99% of plugins. The problem is only in TigerReports in chat messages. In the GUI, the prefix is shown correctly - a red gradient
TigerReports 5.0.13
Vault 1.7.3
LuckPerms

**Comment by MrTigreroux** [comment]
Ok thank you for your precisions, the issue should be fixed in the new [version 5.0.14](https://www.spigotmc.org/resources/tigerreports.25773/update?update=455700). Thank you for reporting it.
