### ISSUE TITLE
Reload permission

### ISSUE THREAD

**Issue by YacuGitHub** [MrTigreroux/TigerReports#113]
Could you please separate tigerreports.manage from the reload command?, for example using tigerreports.reload

The thing is I want to conserve the plugin feature to see IP's for Admins, as we can check on Banned-IPs on the server,

 but I don't want Moderators to see peoples IP's because of security reasons, etc, While Moderators should be able to use 
 "/reports reload" because of sometimes /reports not opening

**Comment by MrTigreroux** [comment]
`/reports` should always open the menu. Do you have any error in the logs ?

**Comment by MrTigreroux** [comment]
Hello, the problem you had should be fixed in the new [version 5.1](https://www.spigotmc.org/resources/tigerreports.25773/update?update=475147). Please let me know if it's not the case.
