### ISSUE TITLE
i cant report anyone

### ISSUE THREAD

**Issue by derehrenputzer** [MrTigreroux/TigerReports#116]
Hey,
I need help.
My problem is that if I /report (player) I can't do that as an op and as a player, it says you can't report to her! Can someone help me on this?

**Comment by MrTigreroux** [comment]
Hello,
You cannot report a player owning the `tigerreports.report.exempt` permission (see all the permissions [here](https://github.com/MrTigreroux/TigerReports/wiki/Permissions)).
I guess that you are trying to report an OP player, but OP players own this permission by default.
For testing purposes, you can report yourself as an OP, but you cannot report other OP players.
If you still cannot report a non OP players who has no permission, try with `/tigerreports:report` command, if it doesn't work too, please send me a screenshot of the problem, and the permissions of the player you are trying to report.

**Comment by derehrenputzer** [comment]
oh thanks thx :)

**Comment by derehrenputzer** [comment]
best plugin ever all goes!

**Comment by MrTigreroux** [comment]
Thank you for the compliment ! :)
