### ISSUE TITLE
Get messages via Bungeecord

### ISSUE THREAD

**Issue by SiriHackYT** [MrTigreroux/TigerReports#122]
Possibility to get all messages with bungeecord, for network it's more simple and we can get all messages

**Comment by MrTigreroux** [comment]
I don't understand what you are requesting.

**Comment by SiriHackYT** [comment]
Possibility to get all message via bungee, if a player leave a spigot server, history message is clear, but with bungeecord we can get all last message of a player

**Comment by MrTigreroux** [comment]
Ok, will see how to do it. Thank you for the suggestion.

**Comment by MrTigreroux** [comment]
Hello, I added that mechanism in the new [version 5.1](https://www.spigotmc.org/resources/tigerreports.25773/update?update=475147). Thank you again for the suggestion.
