### ISSUE TITLE
Suggestion about performing a blocking I/O operation on the main thread

### ISSUE THREAD

**Issue by FunkyNico** [MrTigreroux/TigerReports#123]
Hello, I have found this suggestion from another spigot plugin called [Lagmonitor ](https://github.com/games647/LagMonitor): Make stop the plugin from doing a blocking I/O operation on the main thread because this could affect the server performance, the thread pauses until it gets the response. Such operations should be performed asynchronous from the main thread. Besides gameplay performance it could also improve startup time.

TigerReports Version: 5.0.16 / Server: Purpur-1762 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 39e30d6 on HEAD).

Log: https://logs.apexminecrafthosting.com/feahICZ

Thanks =D

**Comment by MrTigreroux** [comment]
Hello, thank you for this information but it isn't relevant. The "blocking I/O operation" is just a single file read performed after each load of TigerReports. That file contains only one single line, so the operation is really short. There is no impact on server performance, maybe a really small impact on server start time. There is no good reason to make this operation asynchronous as it is only executed once in the normal use of the plugin.
