### ISSUE TITLE
Suggestion: add more placeholders to PunishCommands

### ISSUE THREAD

**Issue by PanGargamel** [MrTigreroux/TigerReports#13]
It would be great to have more placeholders implemented in PunishCommands.
For example, I would like to have report ID automatically added to the ban reason, just to make it easier to process the ban later in case of any appeal or something.
Adding _Reporter_ placeholder would be also great so you could notify the reporter about what punishment has been applied to the player. Another idea is _Admin_, so you could send a message to the player about who punished him.

**Comment by MrTigreroux** [comment]
> I would like to have report ID automatically added to the ban reason
Ok I will add a _Id_ placeholder in the next version, thank you for the idea.

> Adding Reporter placeholder would be also great so you could notify the reporter about what punishment has been applied to the player.
There is already a notification sent to the reporters when their report is processed, you can change it with the message [Messages: Report-notification](https://github.com/MrTigreroux/TigerReports/blob/e3d3613e6c1da439b29ded6520052b55d93579cf/TigerReports/messages/english.yml#L25) in _messages.yml_ file.

> Another idea is Admin, so you could send a message to the player about who punished him.
There is already the `_Staff_` placeholder.

**Comment by MrTigreroux** [comment]
The `_Id_` placeholder has been added in the new [version 4.9.2](https://www.spigotmc.org/resources/tigerreports.25773/update?update=296679). Thank you again.

**Comment by PanGargamel** [comment]
Thanks a lot for a fast response and implementation.
