### ISSUE TITLE
BUG with mysql

### ISSUE THREAD

**Issue by WitheredWinter** [MrTigreroux/TigerReports#131]
**LOGS:**
https://mcpaste.com/cd1cda2ec1c51d572f5ff1a9ffa4ae7a

**DESCRIPTIONS:**
I launched the server and when it loaded TigerReports,the error occurred.Restart did not help.

**MySQL SETTINGS:**
[mysqld]
port = 3306
basedir=D:\MySQL\mysql-5.7.32-winx64
datadir=D:\MySQL\mysql-5.7.32-winx64\data
max_connections=10000
character-set-server=utf8
default-storage-engine=INNODB
sql_mode=NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES
[mysql]
default-character-set=utf8

**SERVER ENVIRONMENT:**
SYSTEM:Windows 10  JDK:16 
Script to launch:"C:\Program Files\Java\jdk-16.0.1\bin\java.exe" -Xmx1G -Xms64m -Dfile.encoding=UTF-8 -Duser.language=zh -Duser.country=CN -jar paper-1.16.5-782.jar nogui
Running in BungeeCord

**PLUGINS:**
![image](https://user-images.githubusercontent.com/123742753/226191702-cb30b476-711c-4a0a-b6b8-c8968a21038d.png)

**Comment by MrTigreroux** [comment]
Hello,
The error explains that your operating system (Windows 10) is not configured to allow enough sockets. You need to increase the maximum amount of sockets allowed by your operating system.
I found this web page that should offer a solution to the problem: https://stackoverflow.com/questions/15433142/mysql-jdbc-communication-exception

**Comment by WitheredWinter** [comment]
I followed the instructions in the guide you provide,and set the MaxUserPort vaule to 65000,but unfortunately the error does not disappear.

**LOG:**
https://mcpaste.com/e94cc2566f97b8d961dc5e858df5471c

**This is what my register look like:**

**Additionally**,the **MaxUserPort** vaule in my computer was 65534 when I opened the issue.And in MySQL settings file,my.ini,the **max_connections** was set to 10000 then.MySQL and my MC servers are in the same physical machine.

**Here are some of my computer parameters:**
System: Windows10  CPU: Intel(R) Core(TM) i7-9700F CPU @ 3.00GHz(3000 MHz)
RAM: 32.00 GB Memory: 512G+1T(2 disks) GPU: NVIDIA GeForce GTX 1660 (6144MB)

Please help me!

**Comment by MrTigreroux** [comment]
Hello, could you try to test only with TigerReports (move all your plugins out of the plugins folder of your server, then restart your server and show me again the full error you get please ?
Did you restarted your computer ?
What did you put as "Host" in MySQL config in config.yml file of TigerReports ?

**Comment by WitheredWinter** [comment]
My HOST is 127.0.0.1.

By the way,the settings of mysql for TigerReports is:
MySQL:
  Host: "127.0.0.1"
  Port: 0
  Database: "omc重构-举报系统"
  Username: "TigerReports"
  Password: "Ndq%wkW69AEe-8u2"
  UseSSL: no
  VerifyServerCertificate: no

**Comment by MrTigreroux** [comment]
Why did you not put port as "3306" ?

**Comment by WitheredWinter** [comment]
Oh,I am so sorry for bothering you with such silly problem.
I did not check my settings of th pluging.
and now the problem is solved.

**Thank you a lot.**You are really a nice and patient developer!

**Comment by MrTigreroux** [comment]
No problem, by the way I recommend you to change your database password

**Comment by WitheredWinter** [comment]
why？Isn't it secure enough?

**Comment by MrTigreroux** [comment]
You just shared it on GitHub, a public website accessible by everyone. This password is no longer secure.

**Comment by WitheredWinter** [comment]
oh,yes.i forget it's a public platform.I will change it.
