### ISSUE TITLE
Problème de performance avec SQL 

### ISSUE THREAD

**Issue by SiriHackYT** [MrTigreroux/TigerReports#134]
Bonjour, j'utilise votre plugin depuis quelques années et j'ai remarqué qu'il y a un gros problème de performance sur une fonction en particulier dans le code qui est : 
fr.mrtigreroux.tigerreports.data.database.Database.startClosing() & fr.mrtigreroux.tigerreports.data.database.Database.closeConnection()

Voici le profiler en question :
![image](https://user-images.githubusercontent.com/49961233/233777913-25aefa03-69d4-4686-a06c-e0c4b3abbeb9.png)

Contexte peut-être utile, base SQL en local, avec + de 180 000 reports et donc beaucoup de joueurs et d'historique

**Comment by MrTigreroux** [comment]
Bonjour, merci de me l'avoir signalé. Je vais voir ce que je peux faire.

**Comment by MrTigreroux** [comment]
Bonjour, le problème devrait être corrigé dans la nouvelle [version 5.1.6](https://www.spigotmc.org/resources/tigerreports.25773/update?update=498493). Merci encore de l'avoir signalé et bonne journée.
