### ISSUE TITLE
EST-CE QUE TU PEUX M'AIDER STP ? CHERCHE COMMENT EXECUTER UN COMMANDE BUNGEECORD

### ISSUE THREAD

**Issue by BEBOUHHHH** [MrTigreroux/TigerReports#137]
Salut, comment ça va ? 
Pourrais tu me dire comment je peux faire en sorte que ton plugin exécute une commande bungeecord d'un plugin custom (le mien) via l'interface de bannissement de TigerReports. J'ai longtemps chercher, et essayer des choses, mais je n'arrive pas.. 

'-CONSOLE tellraw _Staff_ {"text":"[Apply the punish command]","clickEvent":{"action":"run_command","value":"/bungeebancommand _Reported_ 5d Fly"}}'

Cet action ne me correspond pas vraiment, j'aimerais que, quand le staff clic sur une sanction, le joueur est banni ou mute directement (via ton mute de sanction) sans passer par le chat ou autre chose

**Comment by MrTigreroux** [comment]
Salut, ça va très bien merci :)
Malheureusement, ce n'est à ma connaissance pas possible. Les commandes BungeeCord doivent forcément être exécutées par un joueur, et ne peuvent pas être exécutées par un plugin Spigot. C'est pour cela que je propose d'utiliser un message tellraw cliquable.
La solution pour éviter ce tellraw serait donc de faire une commande Spigot (dans un plugin Spigot) pour gérer les sanctions de ton plugin BungeeCord, éventuellement en gérant la communication avec la base de données et/ou le système de communication entre serveurs sur BungeeCord (cf https://www.spigotmc.org/wiki/bukkit-bungee-plugin-messaging-channel/).
