### ISSUE TITLE
Add switch to turn off upgrade check.

### ISSUE THREAD

**Issue by WitheredWinter** [MrTigreroux/TigerReports#140]
Please add an option for us to turn off upgrade check,or make the plugin do the process after the server is fully start.My server for bedwars will take 12s to launch usually,but sometimes,because of Tigerreports' upgrade check,my server take 137s to be ready.It is annoyed!
![image](https://github.com/MrTigreroux/TigerReports/assets/123742753/d9d0e6be-0acc-4ce8-a82f-2344de91a490)
![image](https://github.com/MrTigreroux/TigerReports/assets/123742753/3dbb4072-b014-4d1d-9c9b-d94748382437)
![image](https://github.com/MrTigreroux/TigerReports/assets/123742753/0c09e6d7-2936-4b55-9a56-1b64b325d876)

**Comment by WitheredWinter** [comment]
Some areas in this world have a Great Firewall,as a result the check upgrade process will be really loooooooooooooooong!

**Comment by MrTigreroux** [comment]
I don't think this error message "Failed to get updater check." is from TigerReports. Could you try to remove TigerReports from your plugins folder and test again ?
The update check is done asynchronously, so it shouldn't cause any issue.

**Comment by WitheredWinter** [comment]
Yes,you are right.It is caused by another plugin.I am sorry for bothering you.

**Comment by MrTigreroux** [comment]
No problem, have a good day.
