### ISSUE TITLE
litebans support

### ISSUE THREAD

**Issue by Wonkiest29** [MrTigreroux/TigerReports#145]
add supporting litebans

**Comment by MrTigreroux** [comment]
Hello, you can configure any punishment command in the [Config: Punishments](https://github.com/MrTigreroux/TigerReports/blob/8a9c389fde961c63ba86d3fb1ba4a8d77b533d06/src/main/resources/config.yml#L197-L242) section of the _config.yml_ file.

**Comment by Wonkiest29** [comment]
but if i have litebans on velocity?

**Comment by MrTigreroux** [comment]
I don't know what Velocity is, nor Litebans, but if you have an error or an issue, please describe it in order for me to tell you if I can fix it.

**Comment by Bermiin** [comment]
@MrTigreroux Velocity is a proxy (like Bungeecord or Waterfall is) except that its not a fork of bungeecord or waterfall but a standalone proxy. You can find more information @ https://velocitypowered.com

@Wonkiest29 There is no way for TigerReports to "support" any plugins that are running on your proxy as TigerReports is a spigot plugin. Either move litebans to your spigot server or find a way to execute commands from your spigot server on your proxy.

Either way, this is not TigerReports issue nor can TigerReports fix it.

**Comment by Wonkiest29** [comment]
Okay, thanks
