### ISSUE TITLE
The plugin does not work after the player re-enters the server

### ISSUE THREAD

**Issue by Evalutik** [MrTigreroux/TigerReports#149]
Core: PurPur 1.19.3
PL. ver 5.2.1

PLs, see the video: https://youtu.be/k0c6V0Ha4d8

The plugin works completely, but if I reconnect to the server, the /reports command stops working, and the console is blank
Pls, watch the video:

Config in .txt format:
[config.txt](https://github.com/MrTigreroux/TigerReports/files/12585976/config.txt)

**Comment by Evalutik** [comment]
I checked, it doesn't even depend on config

**Comment by MrTigreroux** [comment]
Hello, thank you for reporting it but the issue was already reported (see #147) and I think that I found a fix.
You can use the 5.1.6 version of TigerReports (available [here](https://www.spigotmc.org/resources/tigerreports.25773/history)) for now, that should normally work.
