### ISSUE TITLE
Lag

### ISSUE THREAD

**Issue by vladyaso** [MrTigreroux/TigerReports#155]
Server crashes due to reports
paper 1.16.5
TigerReports 5.2.2

https://www.youtube.com/watch?v=b1vancfs9Ek

**Comment by MrTigreroux** [comment]
Hello, I don't see any crash in your video.
I notice that you have 20 TPS from the start to the end of your video.
Maybe timings could reveal some issue in the code, if you could try to record a timing (see [documentation](https://www.spigotmc.org/wiki/timings/)) from the start to the end doing the same things that in your video and send me the result it could help me, thank you in advance.

**Comment by vladyaso** [comment]
https://timings.aikar.co/dev/?id=5a9c58c411e84b479587e3ad2c1ccc76#plugins

https://youtu.be/QZo6qesZ2dI

**Comment by vladyaso** [comment]
Hi

**Comment by vladyaso** [comment]
Fix pls !!!!

**Comment by MrTigreroux** [comment]
Hello,
I notice again that you have 20 TPS during all your video.
TigerReports, like any other plugin, consume some resources of your server to run. Maybe it can be improved (I try to do it), but there is no magic solution, it will always impact the performances of your server (but I try to minimize that impact).
Unless you have an idea of what could be improved, or what is the origin of the high timings, I won't be able to fix the issue soon. Spamming with "Fix pls" won't help me, and will probably risk to demotivate me from trying to improve the plugin.
Hoping you can understand it, have a good day.
