### ISSUE TITLE
Disable middle-click archive action when OnlyDoneArchives is set to true

### ISSUE THREAD

**Issue by PanGargamel** [MrTigreroux/TigerReports#16]
`OnlyDoneArchives` option in config disables the `Archive` button in report menu, but it still can be archived using middle-click. It should be disabled in my opinion too.

**Comment by MrTigreroux** [comment]
I fixed it in the new [version 4.9.5](https://www.spigotmc.org/resources/tigerreports.25773/update?update=297456), thank you for reporting this problem.
