### ISSUE TITLE
Add CMI Bungee MSG Support

### ISSUE THREAD

**Issue by Mithranduil** [MrTigreroux/TigerReports#160]
Currently if an player reports an other player its not track the messages that are get send by /msg with CMI Bungee Mode active.
this makes it really disturbing to track MSGs in Reports.

If this could be possible, this would be awesome!

**Comment by MrTigreroux** [comment]
Hello, have you configured "/msg" in [Config: CommandsHistory](https://github.com/MrTigreroux/TigerReports/blob/64644358badb226f23348809954854b0ec7ce7bf/src/main/resources/config.yml#L61-L64) setting in config.yml file ?
