### ISSUE TITLE
ConfigUtils.getInfoMessage (String;String;)String; maybe called before the configuration loads

### ISSUE THREAD

**Issue by zhusun890** [MrTigreroux/TigerReports#161]
When the plugin enables, it invokes
`MenuRawItem.init ()V` (at TigerReports.java, line 84)
and this checks the server version using `VersionUtils.getMinecraftVersion ()I`
when `getMinecraftVersion ()I` caught an NumberFormatException, it calls `ConfigUtils.getInfoMessage (String;String;)String;`
But currently, all configurations wasn't loaded, because they're going to be loaded when `TigerReports.load ()V` was called, but it would've called after the invocation `MenuRawItem.init ()V`, so there might be an NullPointerException being thrown when the plugin enables sometimes.

**Comment by MrTigreroux** [comment]
Hello, thank you for reporting this issue, I just fixed it in the new [version 5.3.3](https://www.spigotmc.org/resources/tigerreports.25773/update?update=542285).
Do not hesitate if you find other issues.
