### ISSUE TITLE
Question for Translate

### ISSUE THREAD

**Issue by Skeec54** [MrTigreroux/TigerReports#17]
is it possibil to help to translate the plugin into other languages? (can help to translate it onto german)

**Comment by MrTigreroux** [comment]
Hello, any help is always welcome.
There is already a translation of (old) messages (the recently added are in english, added by myself) here: 
[![](https://i.imgur.com/nbnV7we.png)](https://raw.githubusercontent.com/MrTigreroux/TigerReports/master/TigerReports/messages/german.yml)
If you want to complete them or write new ones, it's welcome.
Idealy, it would be great to keep the colors (and format) of the messages.

**Comment by Skeec54** [comment]
i saw something in the console maybe that can be translated too? (http://prntscr.com/p4w5va) if possibil (but i don´t know that its saying i thinnk because of the version) and where can i send the messages?
