### ISSUE TITLE
I cant use Terracotta

### ISSUE THREAD

**Issue by AlphaDesigns0** [MrTigreroux/TigerReports#18]
I was setting up the plugin, all was good, but when i want to make the punishments its a little complicated, i cant put terracotta as block in the GUI menu, because your plugin doesnt read it, do you know what can i do? Im in 1.14.4, also i tried to use hardened clay but it doesnt work, help🙃
Other thing, is there an option to fill spaces in the GUI? Like i dont want nothing to be in slot 31 and i just skip it or something?

**Comment by MrTigreroux** [comment]
Answered on SpigotMC forum.
