### ISSUE TITLE
Erreur lors du signalement d'un joueur qui ne s'est jamais connecté. 

### ISSUE THREAD

**Issue by Mrcoco29** [MrTigreroux/TigerReports#2]
C'est de nouveau moi.

Lorsque l'on signale un joueur qui ne s'est jamais connecté, on obtient cette erreur : http://pastebin.com/nV9pfLVe.

Certes, on n'est pas censé signaler des joueurs non existant, mais ça serait plus propre de ne pas avoir d'erreur.

Bonne fin de journée,

Mr_coco29

En tout cas, depuis le temps que je cherche un plugin de signalement et/ou ticket, celui ci est vraiment très intuitif, c'est agréable à utiliser, bravo et merci de partager ton travail.

**Comment by MrTigreroux** [comment]
Le problème est normalement corrigé, merci de l'avoir signalé.

**Comment by Mrcoco29** [comment]
Encore une fois, merci pour la rapidité !

Bonne journée.
