### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by DamsDev1** [MrTigreroux/TigerReports#20]
Bonjour, je vous propose une suggestion sur votre plugin qui serait l'ajout d'une option "useSSL" qui permettra de se connecter à notre base de données en SSL si on le souhaite. Avec le useSSL, je propose aussi une option "verifyServerCertificate" qui vérifira ou non les certificats du serveur avant de se connecter en SSL. Ces deux options pourraient être vraiment utile et ne demande pas beaucoup de temps de développement.

**Comment by MrTigreroux** [comment]
Bonjour, je ne connais pas du tout SSL. Est-ce que vous avez juste besoin de ces 2 booléens ou il faut aussi d'autres paramètres (je crois avoir compris que cela fonctionnait avec des clés, est-ce qu'il faudrait donner un accès à ces clés ou directement les configurer dans le fichier config.yml de TigerReports) ?
Si vous avez une documentation simple dessus je suis preneur.

**Comment by DamsDev1** [comment]
Voici ce que c'est que le SSL (ne sert pas qu'aux sites webs) : https://www.ovh.com/fr/ssl/
D'ailleurs, si vous êtes perdu, voici un plugin qui utilise ces deux options : https://github.com/lucko/LuckPerms
useSSL et verifyServerCertificate sont des options sur la ligne de commande lors de la connexion à la base de données.

**Comment by MrTigreroux** [comment]
Je viens de les ajouter dans la nouvelle [version 4.9.11](https://www.spigotmc.org/resources/tigerreports.25773/update?update=320560). Merci pour votre suggestion et bonne soirée.
