### ISSUE TITLE
make console able to run command /report

### ISSUE THREAD

**Issue by Sprite233** [MrTigreroux/TigerReports#21]
console cant report player by /report playername reason

**Comment by MrTigreroux** [comment]
That is voluntarily prevented. Why would you report players with the console and therefore loose information of the reporter (his messages history, his position, his server, his statistics...) ?

**Comment by Sprite233** [comment]
uhmm just for anticheat xD

**Comment by MrTigreroux** [comment]
Most anticheat have their own alert system, why would you not use it ?

**Comment by Sprite233** [comment]
because my server is bungeecord network

**Comment by MrTigreroux** [comment]
There are anticheat that work with BungeeCord

**Comment by MrTigreroux** [comment]
There are anticheat that work with BungeeCord

**Comment by Sprite233** [comment]
all right..
