### ISSUE TITLE
Command priority

### ISSUE THREAD

**Issue by reussy** [MrTigreroux/TigerReports#22]
Good

More than an error it is a problem that applies to my network.

It turns out that I use the BanManager plugin and it has a / report command and makes TigerReports unuttable since the BanManager / report takes precedence

Maybe with an [aliases] in the plugin.yml that is "treports" or something like that, it would help me a lot

Thank you

**Comment by MrTigreroux** [comment]
You can try with `/tigerreports:report` command.
If it works, then consider using a plugin like MyCommands to link your `/treport` command or whatever you want to `/tigerreports:report` command.
If it doesn't, TigerReports may trigger an error in the logs.
