### ISSUE TITLE
bug when using bungeecord

### ISSUE THREAD

**Issue by KingWeppy** [MrTigreroux/TigerReports#24]
in some server on the network you can't report but all the other commands work is this bug only for me pls tell me

**Comment by KingWeppy** [comment]
but I can use /tigerreports:report

**Comment by MrTigreroux** [comment]
The plugin needs to be installed on each Spigot server.
If you can use /tigerreports:report command but not /report, then it means another plugin is using this command. You have 2 solutions: see if you can change the priority of this command with your other plugin or use a plugin like MyCommands to link /report command to /tigerreports:report command.
