### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by HyperSkys** [MrTigreroux/TigerReports#25]
How do I make it not show a players IP address?
And also how do I get the config file to english

**Comment by MrTigreroux** [comment]
Just remove the `_IP_` placeholders from your _messages.yml_ file (in [these lines](https://github.com/MrTigreroux/TigerReports/blob/a3be887a5fe2fbc8e7fa34b2a62dfc6c1b3ff38e/TigerReports/messages/english.yml#L90-L91)).
English default messages are [there](https://raw.githubusercontent.com/MrTigreroux/TigerReports/master/TigerReports/messages/english.yml).

**Comment by HyperSkys** [comment]
And also it still says [Report - localhost]

**Comment by HyperSkys** [comment]
How you remove that

**Comment by HyperSkys** [comment]
Ok, I Found it 
But I just have a suggestion :) you should add a option to set all of the prefixs would save a lot of time xD

**Comment by MrTigreroux** [comment]
You can use a text editor to replace them at once
