### ISSUE TITLE
Litebans | Report with Tiger Reports

### ISSUE THREAD

**Issue by HyperSkys** [MrTigreroux/TigerReports#26]
While a player is punished even with default essentials mute when they try and report someone It will alert them that they are still muted.

Does it make you say a chat message or like a command?

**Comment by HyperSkys** [comment]
The report will not even go through

**Comment by HyperSkys** [comment]
![2020-06-20_01 26 26](https://user-images.githubusercontent.com/66301237/85195109-643fde80-b295-11ea-8c05-a3282f02896b.png)

**Comment by MrTigreroux** [comment]
TigerReports doesn't manage mute. That means that the /report command is blocked by your mute plugin, not by TigerReports and the message you get doesn't seem to be one of TigerReports. 
Maybe i didn't understand your problem but in your screen i don't see any message of TigerReports nor any command.
