### ISSUE TITLE
Error loading plugin on 1.15.2

### ISSUE THREAD

**Issue by ManO1234148** [MrTigreroux/TigerReports#27]
Running 1.15.2 and i get this error on trying to run the plugin

Error enabling plugin TigerReports
24.06 23:41:47 [Server] INFO java.lang.NoClassDefFoundError: org/bukkit/plugin/java/JavaPlugin
24.06 23:41:47 [Server] INFO at java.lang.ClassLoader.defineClass1(Native Method)
24.06 23:41:47 [Server] INFO at java.lang.ClassLoader.defineClass(ClassLoader.java:757)
24.06 23:41:47 [Server] INFO at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
24.06 23:41:47 [Server] INFO at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
24.06 23:41:47 [Server] INFO at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
24.06 23:41:47 [Server] INFO at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
24.06 23:41:47 [Server] INFO at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
24.06 23:41:47 [Server] INFO at java.security.AccessController.doPrivileged(Native Method)
24.06 23:41:47 [Server] INFO at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
24.06 23:41:47 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
24.06 23:41:47 [Server] INFO at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:44)
24.06 23:41:47 [Server] INFO at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:37)
24.06 23:41:47 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
24.06 23:41:47 [Server] INFO at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:327)
24.06 23:41:47 [Server] INFO at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:235)
24.06 23:41:47 [Server] INFO at net.md_5.bungee.BungeeCord.start(BungeeCord.java:272)
24.06 23:41:47 [Server] INFO at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
24.06 23:41:47 [Server] INFO at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
24.06 23:41:47 [Server] INFO Caused by: java.lang.ClassNotFoundException: org.bukkit.plugin.java.JavaPlugin
24.06 23:41:47 [Server] INFO at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:63)
24.06 23:41:47 [Server] INFO at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:37)
24.06 23:41:47 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
24.06 23:41:47 [Server] INFO ... 18 more

**Comment by MrTigreroux** [comment]
TigerReports isn't a BungeeCord plugin but a Spigot one which interacts with BungeeCord network.
Please read the Installation section of the [presentation page](https://www.spigotmc.org/resources/tigerreports.25773/) of the plugin to completely know how to use it.
