### ISSUE TITLE
TigerReports not Working

### ISSUE THREAD

**Issue by ImTomOriginal** [MrTigreroux/TigerReports#29]
Hello. Im using TigerReports on version 1.8.8 with mysql. Everything worked fine when i was on one server but when i upload plugin on all server and connect it to mysql it just dont work... When i try to report someone it make the sound of send but nothing happened. Please help :) Thanks

**Comment by MrTigreroux** [comment]
Hello,
- Do you have any error in the logs/console ? If yes could you copy/paste it please.
- What version of TigerReports do you use ?
- Is there the `The plugin is using a MySQL database.` or `Le plugin utilise une base de donnees MySQL.` message at the start of your server (in the logs/console) ?
- Are your other servers running Spigot or PaperSpigot or something else ?
- Is TigerReports written in green in `/plugins` command on all your servers ?
