### ISSUE TITLE
Hey, it's AZFire from Spigot (not an issue)

### ISSUE THREAD

**Issue by AZFire1** [MrTigreroux/TigerReports#30]
My review was not wanting to disable it showing your credits and that you made the plugin... No, no, no.. I just wanted to disable /tigerreport(s).. People can still do /report help and see it's your plugin. I really like the plugin, I'm not trying to hide it was made by you. I posted here because I can't post on spigot more than one comment. Sorry D:

**Comment by AZFire1** [comment]
Sorry, I don't care to. I just wanted to know if there way a way. Didn't wanna offend you. I understand it took time to make the plugin, it's an awesome plugin!

**Comment by MrTigreroux** [comment]
I still don't understand why you would need/want to remove this command that probably not many people will use or even know, but no, you can't remove/hide it. I'm not offended, just wanted to explain you why it is not hideable.
Thank you for the compliment, have a good day
