### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by Troopsdv** [MrTigreroux/TigerReports#32]
I was wondering on how to change the language on your Tiger Reports, it seems really good right now, just the server im helping with is mainly all English speaking, so i would love to know on how to change the language

**Comment by MrTigreroux** [comment]
You can change the language used in console messages by putting "English" for [`Config: InfoLanguage`](https://github.com/MrTigreroux/TigerReports/blob/ce256058b7d25b84f36a57de5c9f913721e0a780/TigerReports/src/config.yml#L12) setting in config.yml file.
And you can change the messages of the plugin in the file messages.yml with, for example, the [default english messages](https://raw.githubusercontent.com/MrTigreroux/TigerReports/master/TigerReports/messages/english.yml).
