### ISSUE TITLE
Hello~ I have a complete Chinese language text

### ISSUE THREAD

**Issue by SakuraTao2007** [MrTigreroux/TigerReports#34]
Hello author! I have a complete Chinese language text
now I will send it to you
hope you can update! 
This text fixes a lot of wrong statements
hope it will apply!
https://qingchenmowang-my.sharepoint.com/:u:/g/personal/sakuratao_qingchenmowang_onmicrosoft_com/ESQ0FDCgPGlAjKqFW3Kc2owBOCbsbhKgf2x6vMxGUq--Dg?e=6xr7bi

**Comment by MrTigreroux** [comment]
Hello, thank you for your help.
But your messages are mostly the same as the ones of lvyitian/merganser. You added strange points and ">>" characters and removed some "&e" that doesn't fit with the "standard" format of default messages.
So I will keep the ones of lvyitian/merganser. But still, thank you for the help.
