### ISSUE TITLE
Tigerreports /tigerreports translation

### ISSUE THREAD

**Issue by ShreyasAyyengar** [MrTigreroux/TigerReports#35]
Hi there,

I have the latest version of tigerreports and when I do /tigerreport the help message comes up in french. Is there a way to change that?

Thanks,
Shreyas

**Comment by MrTigreroux** [comment]
Hi,
You can put it in english by setting `Config: InfoLanguage` setting to `English` in _config.yml_ file.
You can change the text of the commands with the `Messages: Help-commands` message in _messages.yml_ file.
