### ISSUE TITLE
Suggestion: Archived reports sorting order

### ISSUE THREAD

**Issue by piotrskibapl** [MrTigreroux/TigerReports#36]
Currently, the archived reports are sorted from the oldest one to the newest one.
In my opinion, it would be easier if they would be sorted from the newest one to the oldest one - when the user opens the archived reports GUI, most likely he'll be looking for some of the latest archived reports.
As for now, I have 33 pages of archived reports on my server and if I archive some report mistakenly, I have to scroll through these 33 pages to unarchive it.

**Comment by MrTigreroux** [comment]
Effectively, it is more useful to sort them in the opposite order.
Changed in new [version 4.11.7](https://www.spigotmc.org/resources/tigerreports.25773/update?update=357872), thank you for suggesting it.
