### ISSUE TITLE
Marking report as abusive doesn't archive it

### ISSUE THREAD

**Issue by piotrskibapl** [MrTigreroux/TigerReports#37]
The current behavior of the plugin is that it automatically archives reports after resolving it (I can't remember if that's the default behavior or I set it in the config).
However, marking report as abusive (the golden axe GUI item) will mark the report as false, but the report will not be archived.
Could that be changed?

**Comment by MrTigreroux** [comment]
That is the default behavior for people owning `tigerreports.staff.archive.auto` permission.
Fixed in new [version 4.11.7](https://www.spigotmc.org/resources/tigerreports.25773/update?update=357872). Thank you for reporting it.
