### ISSUE TITLE
Other staff members can't see report resolved notifications

### ISSUE THREAD

**Issue by piotrskibapl** [MrTigreroux/TigerReports#38]
Assuming that there are two online moderators on the server, and one moderator processes a report, the other online moderator won't see any notification about that. I'm pretty sure that a few months ago it was working fine.

I'm not sure if it's caused by the plugin bug or it's due to my configuration, but I didn't see any permissions for that so I would appreciate it if you could check if it's the plugin fault or not.

TigerReports-related permissions I have for the moderator group:
 - tigerreports.staff
 - tigerreports.staff.archive
 - tigerreports.staff.archive.auto
 - tigerreports.staff.teleport
 - tigerreports.staff.advanced

TigerReports config: https://gist.github.com/piotrskibapl/dc8b926265514eac7f8c27194076da8e
TigerReports version: 4.11.6

**Comment by MrTigreroux** [comment]
I made a mistake in the code while factorizing it, thank you for pointing it.
Fixed in new [version 4.11.7](https://www.spigotmc.org/resources/tigerreports.25773/update?update=357872).
