### ISSUE TITLE
Messages history doesn't contain commands set in the config

### ISSUE THREAD

**Issue by piotrskibapl** [MrTigreroux/TigerReports#39]
I have the following section added in the config.yml:
```
CommandsHistory:
   - msg
   - message
   - w
   - whisper
   - tell
   - vc
```
However, I still can't see any of these commands in the messages history of the report - I can only see the chat messages.

**Comment by MrTigreroux** [comment]
I made a mistake since the addition of this feature without testing it again. Thank you for notificing that it now longer worked.
Fixed in new [version 4.11.7](https://www.spigotmc.org/resources/tigerreports.25773/update?update=357872).
