### ISSUE TITLE
Messages not translated

### ISSUE THREAD

**Issue by NotPlayerBlade** [MrTigreroux/TigerReports#41]
I put in the english message file, but some are not translated. Look at this pic:
![image](https://user-images.githubusercontent.com/72660172/96197552-6dc61400-0f20-11eb-9072-c25b6a2c9d47.png)

**Comment by MrTigreroux** [comment]
Hello,
Some messages are not updated after a simple reload for performance reasons.
Just restart your server (**not** with `/reload` command) and all messages will be updated.

**Comment by MaximMaximS** [comment]
...also some messages are in config.yml
