### ISSUE TITLE
1.16.3 Support?

### ISSUE THREAD

**Issue by snaildos** [MrTigreroux/TigerReports#42]
Can't get the plugin to load up on Bungeecord on 1.16.3?

**Comment by MrTigreroux** [comment]
TigerReports is a Spigot plugin, it cannot be installed on a BungeeCord server but will still work with the BungeeCord network.
Please read the Installation section of the [presentation page of the plugin](https://www.spigotmc.org/resources/tigerreports.25773/).
If the plugin doesn't work on Spigot, there must be an error in the console/logs. Please copy/paste it here.

**Comment by snaildos** [comment]
I see, thank you :)))
