### ISSUE TITLE
1.16 support for waterfall

### ISSUE THREAD

**Issue by Edwek** [MrTigreroux/TigerReports#45]
Can you add 1.16 support?
Plugin is not loading on waterfall.

**Comment by Edwek** [comment]
You said there's Bungeecord Support.

**Comment by Edwek** [comment]
![image](https://user-images.githubusercontent.com/74269968/102096809-69857c80-3e25-11eb-9ec6-6bcd74d6b95c.png)

**Comment by MrTigreroux** [comment]
That's not a BungeeCord plugin, please read the installation section of the plugin to understand how to use the plugin.

**Comment by Edwek** [comment]
You have to configure a MySQL database in config.yml file (at the bottom of the file) on each of your Spigot servers and leave the BungeeCord option enabled.
(You don't have to put TigerReports.jar in the plugins folder of the BungeeCord network.)

Since the plugin is not loading, how I am supposed to setup a MySQL database?

**Comment by Edwek** [comment]
Edit: As I'm understanding, the plugin goes to spigot server . But how It's supposed to work in bungeecord (every server) database can't do this?

**Comment by MrTigreroux** [comment]
Yes, as written in the installation section, the plugin must be installed on each of your Spigot servers.
It will work with BungeeCord if the setting in config.yml is enabled. I don't use database for communication with BungeeCord but the BungeeCord plugin messaging channel, which is a feature of Spigot.
