### ISSUE TITLE
Timings

### ISSUE THREAD

**Issue by Fantom250YT** [MrTigreroux/TigerReports#49]
<img width="1573" alt="Screenshot 2021-01-11 at 08 23 28" src="https://user-images.githubusercontent.com/73852683/104159309-0288c280-53e7-11eb-90f4-1aada072c6d8.png">

Is this normal?

**Comment by MrTigreroux** [comment]
I guess it is. If you have many players, it is normal that many events are triggered. All queries are asynchronous in order to don't slow down the main thread on which Spigot run.
I don't see what more I can do to reduce lags, but if you have suggestions they are welcome.

**Comment by Fantom250YT** [comment]
Hi, Thanks for your response!

These are todays timings and Tiger reports is pretty high, and might be causing issues.
https://timings.aikar.co/?id=e2d6c843816e403e93850435f78863c1

Anyway I can fix it?
Thanks

**Comment by MrTigreroux** [comment]
After reading again the code, I found a mistake in the way I access to the database for reports notification.
I fixed it in new [version 4.11.9](https://www.spigotmc.org/resources/tigerreports.25773/update?update=381259). Thank you for reporting it, hope it will fix the lags you have.
