### ISSUE TITLE
How do I use the bungee plugin's command to punish someone

### ISSUE THREAD

**Issue by mehmetofficial68** [MrTigreroux/TigerReports#50]
The plugin is using the tempban command as the essentials command. I'm using advancedban on my bungee server for the ban system. How do I get the advanced ban plugin to use the command when I type tempban while penalizing.

**Comment by MrTigreroux** [comment]
You guess right. Please have a look at this section of the [presentation page](https://www.spigotmc.org/resources/tigerreports.25773/) of the plugin.
![](https://i.imgur.com/O9I0typ.png)
If it doesn't help you, let me know it.

**Comment by mehmetofficial68** [comment]
thanks i understand. spigot plugin dont use bungee command. how can i use tellraw.

**Comment by mehmetofficial68** [comment]
can i do this automatically.
By the way, I browsed the plugin page, but I just saw it there, because my native language is not English, I could not notice it. sorry

**Comment by mehmetofficial68** [comment]
Can we do this automatically instead of clicking on the message or how do I change the color of the message.

**Comment by MrTigreroux** [comment]
No you can't force a player, with a Spigot plugin, to execute a command to the BungeeCord network. That's why there is this "trick" with tellraw. Use a tellraw generator to change color of the message.

**Comment by mehmetofficial68** [comment]
i got it i rewrote all commands with tellraw and it worked really thank you very much. The plugin is really good quality. bless your hands

**Comment by mehmetofficial68** [comment]
now i use it like this
`- '-CONSOLE tellraw _Staff_ {"text":"Cezayı onaylamak için tıklayınız.","color":"green","clickEvent":{"action":"run_command","value":"/tempban _Reported_ 1d Otomasyon"}}'`

**Comment by mehmetofficial68** [comment]
thanks for help

**Comment by MrTigreroux** [comment]
You are welcome :)
