### ISSUE TITLE
Duplication of Notice Messages

### ISSUE THREAD

**Issue by PixelDev0** [MrTigreroux/TigerReports#53]
Hello,

I have recently installed this plugin on my server. My current thoughts about it are really good! I have noticed one issue however. When a player opens a report using the /report command, staff members get two notifications about it. I am using a MySQL database with the TigerReportsSupports plugin installed.

Any help would be appreciated. Thanks.

**Comment by MrTigreroux** [comment]
Hello, I think that you installed TigerReportsSupports on more than 1 Spigot server. You must remove it from all your Spigot servers except 1.
If it's not the case, please give me screenshots of the problem.

**Comment by PixelDev0** [comment]
At the moment, I have only set the plugins up on one server with MySQL. Attached is a screenshot of the issue.
![image](https://user-images.githubusercontent.com/67294530/107159717-c0e93880-69e1-11eb-9364-e45d8b5ace50.png)
![image](https://user-images.githubusercontent.com/67294530/107159727-d199ae80-69e1-11eb-9630-511c647ebbbf.png)

Also, when the report is updated, only the second discord embed is edited.

Thanks

**Comment by MrTigreroux** [comment]
Please check again because there is no reason to have 2 messages. The only time a user got 2 messages was because he installed TigerReportsSupports on 2 Spigot servers.

**Comment by PixelDev0** [comment]
I have checked again and I am one hundred percent certain that there is only one server that both the plugins are still only installed on one server, being my test server.

**Comment by MrTigreroux** [comment]
Ok, then please remove TigerReportsSupports and check if there is still the double message.

**Comment by PixelDev0** [comment]
I have just tried to remove the TigerReportsSupports plugin and this issue is still occuring.

**Comment by MrTigreroux** [comment]
And do you still get a message on Discord ?

**Comment by PixelDev0** [comment]
No

**Comment by MrTigreroux** [comment]
Ok, without TigerReportsSupports you have no message on Discord and 2 alert messages on your Spigot server. Maybe you pasted 2 times TigerReports plugin on your server plugins folder ?

**Comment by PixelDev0** [comment]
I have double checked that the plugin only exists once on the server.
No, I have not yet tried to reset `config.yml`. I will do that now.
Yes, all messages that get sent to staff members get duplicated.
Yes, the alert is duplicated in the console logs aswell.
I am using Purpur 1.16.5 using the latest build.

**Comment by MrTigreroux** [comment]
Could you try to set `BungeeCord: Enabled`  setting to false in config.yml file, then restart your server and check if the messages are still duplicated ?

**Comment by PixelDev0** [comment]
Sorry for not responding for a while.

I have disabled the BungeeCord option and this has fixed the entire issue (including the duplication of the discord messages).

**Comment by MrTigreroux** [comment]
Ok, that means that your server receives the BungeeCord messages that himself send to the other servers, which is not how Spigot work normally. The BungeeCord messages are meant to be sent to others servers and not "detected"/"processed" by the server sending them. Maybe you have an option to disable this behaviour.

**Comment by PixelDev0** [comment]
I'll have a look but I am not fully understanding this answer. If possible, please explain more.

**Comment by MrTigreroux** [comment]
When a **Spigot** server sends a BungeeCord message to others servers, this message isn't processed as a "received" message for this server that has sent that message. It seems that a **Purpur** server doesn't work like this. It catches the message it sent himself, which induce the double message you got.
Said in other words, your server sends the message to all servers of the BungeeCord network, including himself, whereas a Spigot server sends the message to all servers except himself (which makes much sense, there is no need to process as "received" a message that we send).

**Comment by PixelDev0** [comment]
Ok, well I recently downgraded my servers to 1.8 and 1.9 (1.9 because of plugin compatibility) and also moved to a dedicated server so I will have to use Paper (my choice) or Spigot. The issue is fixed. Thanks for your help.
