### ISSUE TITLE
Error with database 

### ISSUE THREAD

**Issue by Fantom250YT** [MrTigreroux/TigerReports#54]
So it's the same config on all the servers but on my hub this error is happening
https://pastebin.com/fS2PLKeA

**Comment by MrTigreroux** [comment]
As written in the error, it seems that you deleted the table `tigerreports_users`.  Try restarting your server and it should be fixed.

**Comment by Fantom250YT** [comment]
I haven't touched the table though, maybe when I added the hub to it after skyblock and survival it deleted the old user one

**Comment by MrTigreroux** [comment]
I guess it is now fixed. If not please tell me.
