### ISSUE TITLE
Syntax not accepted

### ISSUE THREAD

**Issue by HackerSte** [MrTigreroux/TigerReports#55]
Hi! I have installed TigerReports but I can't submit report. This is the error I get:
![image](https://user-images.githubusercontent.com/68558172/111869144-2b48ad80-897e-11eb-8443-4144165508ef.png)
How I can solve this?

**Comment by MrTigreroux** [comment]
If you didn't change the messages.yml file of TigerReports, this message isn't sent by TigerReports plugin.
Try to use `/tigerreports:report` command. I think that you have another plugin using/blocking the `/report` command.

**Comment by HackerSte** [comment]
I did some tests and found that the plugin giving problems is Custom Plugin List. Thanks for your help!

**Comment by MrTigreroux** [comment]
You are welcome. Happy to know you succeeded to fix it :)
