### ISSUE TITLE
Split Menus.Report-details text into two separate ones

### ISSUE THREAD

**Issue by piotrskibapl** [MrTigreroux/TigerReports#57]
Hi,

I am encountering a problem with removing the admin username from the chat messages of the plugin. I don't want to display the admin username as the staff can be vanished and it makes players aware of which admin is online.

I have a problem with one of the texts - `Menus.Report-details`
Its key suggests that it should be used in the GUI only, but it is also used in a chat message that is sent to user when his report was processed (when you hover over the report ID, this message will be displayed).
I could of course just remove the `_Status_` from here, but then the admin username would not also be visible in the GUI for other staff members.

Could this text be splitted into two separate ones?

**Comment by MrTigreroux** [comment]
Added in new [version 4.12.7](https://www.spigotmc.org/resources/tigerreports.25773/update?update=401262). Thank you for the suggestion.

**Comment by MrTigreroux** [comment]
It could be added but then you would have it even when the report is not processed (waiting, in progress, ...). You will have something like "Appreciation: None". Is it what you want ?

**Comment by piotrskibapl** [comment]
This would be fine for me. Another option would be a `_ShortStatus_`, which would be basically the same as `_Status_`, but without the admin username (that's what I want to achieve). However, in my case, both solutions would be sufficient for me.
