### ISSUE TITLE
Add possibility to disable text trimming in GUI titles

### ISSUE THREAD

**Issue by piotrskibapl** [MrTigreroux/TigerReports#59]
Hi,

I am currently working on getting TigerReports to work with Triton (it's a plugin that allows you to have your messages translated into multiple languages - https://www.spigotmc.org/resources/triton-translate-your-server.30331/).

While it works fine with regular chat messages, I found a problem that is caused by TigerReports trimming the menu title if it's too long. Basically, Triton works by replacing a placeholder text with text from the translations - so instead of a proper message in the messages.yml, you should provide something like `[lang]someplugin.some.key[args][arg]%argument%[/arg][/args][/lang]` and Triton will provide the message basing on users language.

This is the part that doesn't work properly with TigerReports - as TigerReports is trimming menu titles, the text above is changed to, let's say, `[lang]someplugin.some...` and because of this Triton will not replace this text.

My suggestion would be to have an additional config item in the config - `trim-too-long-menu-texts: true` or `triton-support: true`.

**Comment by MrTigreroux** [comment]
The problem is that if title is not trimmed, the Bukkit API throws an error because Minecraft inventories title cannot be longer than 32. All I can suggest is to request to the author of the plugin "Triton" to add custom short placeholders like `[short_placeholder]` pointing to `[lang]someplugin.some.key[args][arg]%argument%[/arg][/args][/lang]`

**Comment by piotrskibapl** [comment]
@MrTigreroux is this still a limitation?
I can see that some plugins allow to use titles longer than 32 chars.
I also tried creating a custom inventory with the following code, and it works fine with 50 chars:
```
Bukkit.createInventory(this, 6 * 9, "01234567890123456789012345678901234567890123456789");
```

**Comment by MrTigreroux** [comment]
According to md_5, author of Spigot, the limit is set on client (old ?) versions of Minecraft (https://www.spigotmc.org/threads/ignore-title-length-limit-in-inventory.409718/#post-3638527). What version of Minecraft do you use ?

**Comment by piotrskibapl** [comment]
I'm currently on 1.16.5. I'm not 100%, but I think I can remember that inventory names longer than 32 characters were working also on 1.12.2.

**Comment by MrTigreroux** [comment]
I finally found the time to test versions and find that the limit of 32 characters only concerns versions lower than 1.9. Titles are no longer trimmed in new [version 4.12.8](https://www.spigotmc.org/resources/tigerreports.25773/update?update=407158) for versions higher than 1.8. Thank you for noticing the improvement.
