### ISSUE TITLE
messages.yml

### ISSUE THREAD

**Issue by Twiistrz** [MrTigreroux/TigerReports#6]
Delete-details is not translated
![image](https://user-images.githubusercontent.com/25744238/46445731-ea0eb400-c7aa-11e8-9176-0a0c2cc37cfa.png)
![image](https://user-images.githubusercontent.com/25744238/46445752-fb57c080-c7aa-11e8-8131-4f0201932de2.png)

**Comment by Twiistrz** [comment]
Also the Cancel-process-details
![image](https://user-images.githubusercontent.com/25744238/46445807-2f32e600-c7ab-11e8-891f-d0d617234de0.png)

**Comment by MrTigreroux** [comment]
Hello, you can update these messages by restarting your server. They are not updated after reload for performance reasons.

**Comment by Twiistrz** [comment]
Thank you, fixed it.
