### ISSUE TITLE
RGB Support

### ISSUE THREAD

**Issue by untuned** [MrTigreroux/TigerReports#60]
Some of the prefixes in the server I'm helping include RGB color codes. It would be nice to support them to show properly, instead of showing the value.

There are many different ways plugins support hex values, but the most widely accepted one I've come across is `&#RRGGBB`.

Example is the "In Progress" status for reports, it shows the prefix and username next to the report.
![Example of broken hex](https://user-images.githubusercontent.com/7635652/117562908-5c855600-b070-11eb-93bd-be3beab4ea7a.png)

**Comment by MrTigreroux** [comment]
Ok, will try to implement it with this format of hex.

**Comment by MrTigreroux** [comment]
I finally found time to implement the support of this format for hex colors in new [version 4.12.8](https://www.spigotmc.org/resources/tigerreports.25773/update?update=407158). Thank you for the suggestion.
