### ISSUE TITLE
Latest version dont work

### ISSUE THREAD

**Issue by matej1212** [MrTigreroux/TigerReports#61]
I tested all versions and only latest didnt work is problem java 11 or?

**Comment by MrTigreroux** [comment]
Can you copy/paste the error you have in the console/logs please ? What do you mean by "all versions" and "didnt work" ?

**Comment by matej1212** [comment]
Error occurred while enabling Tigerreports v4.12.7 (is it up to date?)

**Comment by MrTigreroux** [comment]
I need all the lines before and after this.

**Comment by matej1212** [comment]
Le plugin utilise Bungeecord

**Comment by MrTigreroux** [comment]
Ok, I need the full logs. Hide IPs/sensible information by replacing them with "****" and paste the logs full last logs file please.

**Comment by MrTigreroux** [comment]
Try the new [version 4.12.8](https://www.spigotmc.org/resources/tigerreports.25773/update?update=407158), it should fix your problem.
