### ISSUE TITLE
TigerReports Language

### ISSUE THREAD

**Issue by plebalol1231** [MrTigreroux/TigerReports#63]
i changed the language to english in config but still all messages are french

**Comment by MrTigreroux** [comment]
Please read the first line of your file. You need to encode the file in the right format, then save, then restart your server (not just using `/reports reload`) command because this command doesn't support all messages.

**Comment by plebalol1231** [comment]
its already encode to UTF-8 and its not working...why there are french language by default idk

**Comment by MrTigreroux** [comment]
What is the Minecraft version of your server (use `/icanhasbukkit` in the Minecraft chat/console to see it).

**Comment by plebalol1231** [comment]
1.16.5 but i just copy pasted the english translation...

**Comment by plebalol1231** [comment]
what is the placeholder for id message?

**Comment by MrTigreroux** [comment]
> 1.16.5 but i just copy pasted the english translation...

Open the messages.yml file with Notepad++, click on the `Encode` tab at the top of the window, select "UTF-8", then save the changes (`Ctrl` & `S` keys) then restart your server. The messages should be updated. If it's not the case, please upload your file there (not just copying the contents but uploading the messages.yml file (drag and drop the file in the reply section of this webpage)).

> what is the placeholder for id message?

I don't understand what you mean by "id message".

**Comment by RadwolfYT** [comment]
How do I get the English?
