### ISSUE TITLE
French and English

### ISSUE THREAD

**Issue by RadwolfYT** [MrTigreroux/TigerReports#68]

**Comment by RadwolfYT** [comment]
I am on using Notepad++ Because I am using a website to host, not on my PC

**Comment by MrTigreroux** [comment]
I guess some of your messages are in french. Just restart your server and all messages will be updated.

**Comment by RoyalCraft397** [comment]
> Sanırım bazı mesajlarınız Fransızca. Sadece sunucunuzu yeniden başlatın ve tüm mesajlar güncellenecektir.

Tiger Reports Turkish patch is out !! There are a lot of Turkish users, but they have difficulty in using it because it is a different language. If you remove the Turkish patch, the use of TigerReports will increase by 10%. I am sure of that

**Comment by MrTigreroux** [comment]
> > Sanırım bazı mesajlarınız Fransızca. Sadece sunucunuzu yeniden başlatın ve tüm mesajlar güncellenecektir.
> 
> Tiger Reports Turkish patch is out !! There are a lot of Turkish users, but they have difficulty in using it because it is a different language. If you remove the Turkish patch, the use of TigerReports will increase by 10%. I am sure of that

I don't know what you call "Turkish patch" but turkish users have no specific obligation of any kind. Please create your own issue describing your problem instead of using this issue that has nothing related to Turkish.
