### ISSUE TITLE
Edit gui slots

### ISSUE THREAD

**Issue by lBoyka** [MrTigreroux/TigerReports#69]
Hello, I have a suggestion, is that you can edit the slots of each gui that opens, that would be great.

**Comment by MrTigreroux** [comment]
Hello,
This would require too much time of development, would considerably reduce performances of the plugin and would introduce many problems especially with bad settings.
Added to that, this would make the configuration of the plugin really complex.
It wouldn't make the plugin more useful, it would just allow people to customize it more.
I think that you can understand that I don't want to spend time on this suggestion. But if you really want custom GUIs, the best is to learn by yourself how to create Java plugins for Minecraft and then make your own plugin or find someone that has this knowledge and wants to make the plugin you want.
Indeed, if slots of each GUI are editable, why would the inventories (that is to say the amount of inventories to display when you process a report for example) not be editable too, then why the commands too ? Choices have been made and it is really difficult to allow the customization of every aspect of a plugin/program.
