### ISSUE TITLE
Tiger Reports prefix

### ISSUE THREAD

**Issue by Gnoarn** [MrTigreroux/TigerReports#7]
Is there a possibility that we can get a prefix configuration in the config that way it can be done once instead of 100 times to change it through the entire messages file

**Comment by MrTigreroux** [comment]
Hello,
I'm sorry but it's deliberately not the case to allow people to put a prefix where they want and in the messages they want.
However, you can use a program like [Notepad++](https://notepad-plus-plus.org/fr/) to easily replace the prefix this way;
- Click on **Search > Replace...**
- Fill the first field with "**&7[&6Report&7]**", the second with the prefix you want to use.
- Click on **Replace all** button.
- Save the changes (encoding in _ANSI_ or _UTF-8_ depending of your Minecraft server version).
