### ISSUE TITLE
Le joueur ne s'est jamais connecté au serveur

### ISSUE THREAD

**Issue by Loubafritz** [MrTigreroux/TigerReports#71]
Yo, j'ai un problème je me connecte avec mon compte Mojang Loubafritz je me déconnecte et quand je veux me report: "Le joueur Loubafritz ne s'est jamais connecté au serveur." Je vous remercie de votre aide en avance

**Comment by MrTigreroux** [comment]
Salut,
Est-ce que tu peux me copier/coller la ligne de `Config: Notifications: Delay` de ton fichier config.yml s'il te plait ?
Essaie de te connecter, de rester 5 minutes sur le serveur, puis de te déconnecter et réessayer de te report.

**Comment by Loubafritz** [comment]
> Salut,
> Est-ce que tu peux me copier/coller la ligne de `Config: Notifications: Delay` de ton fichier config.yml s'il te plait ?
> Essaie de te connecter, de rester 5 minutes sur le serveur, puis de te déconnecter et réessayer de te report.
> Est-ce que tu utilises une base de données MySQL ou SQLite (par défaut) ?

Ma ligne est: Delay: 2. Veut tu que je t'envoie ma config.yml ?
Oui je suis connecté à une MySQL
Je vais essayer de rester co plusieurs minutes.

**Comment by Loubafritz** [comment]
Je suis resté 5min connecté mais rien n'y fais toujours le même message...

**Comment by MrTigreroux** [comment]
D'accord merci.
Et est-ce qu'il y a une erreur dans la console/logs au moment où tu te connectes ou au moment où tu te déconnectes ?
Est-ce qu'il y a bien un message indiquant que le plugin TigerReports utilise la base de données MySQL à son lancement (au début du dernier fichier de logs, préfixe `[TigerReports]`) ?

**Comment by Loubafritz** [comment]
Je me connecte aucune erreur de TigerPlugin ou d'un autre Plugin quand je start le serveur ou que je reload ce message apparaît: [TigerReports] Le plugin utilise une base de donnees MySQL.

**Comment by MrTigreroux** [comment]
Lorsque tu déconnectes Loubafritz de ton serveur, tu essaies de le signaler via un autre compte connecté au serveur ou via la console ?
Essaie de faire `/reports user Loubafritz` lorsque Loubafritz est connecté et lorsqu'il est déconnecté. Est-ce que le menu s'ouvre dans les 2 cas ? Est-ce qu'il affiche des données (tu peux rajouter une statistique par exemple le nombre de signalements envoyés pour tester si la statistique est bien sauvegardée et affichée lorsque Loubafritz est déconnecté).

**Comment by Loubafritz** [comment]
Quand Loubafritz est déconnecté j'essaye de le report avec un autre compte connecté au serveur. Je fais sur le même serveur, je suis sous PaperMC. Quand je fais /reports user le menu s'ouvre quand je suis connecté et déconnecte.

> Lorsque tu déconnectes Loubafritz de ton serveur, tu essaies de le signaler via un autre compte connecté au serveur ou via la console ? Et sur le même serveur Spigot ou sur un autre serveur Spigot que celui où il était connecté ?
> Essaie de faire `/reports user Loubafritz` lorsque Loubafritz est connecté et lorsqu'il est déconnecté. Est-ce que le menu s'ouvre dans les 2 cas ? Est-ce qu'il affiche des données (tu peux rajouter une statistique par exemple le nombre de signalements envoyés pour tester si la statistique est bien sauvegardée et affichée lorsque Loubafritz est déconnecté).

Quand Loubafritz est déconnecté j'essaye de le report avec un autre compte connecté au serveur. Je fais sur le même serveur, je suis sous PaperMC. Quand je fais /reports user le menu s'ouvre quand je suis connecté et déconnecte.

**Comment by MrTigreroux** [comment]
Quelle version de PaperMC utilises-tu (`/icanhasbukkit` pour le voir dans le chat/console) ? Quelle version de TigerReports (`/ver TigerReports` pour le voir) ?
Est-ce que tu écris bien le pseudo "Loubafritz" avec une majuscule au début lorsque tu essaies de le signaler via `/report` ?
Est-ce qu'il y a au moins une statistique non nulle dans le menu `/reports user Loubafritz` ? Si elles sont toutes à 0, fais clic gauche sur l'une d'entre elles pour l'augmenter de 1, puis réessaie d'ouvrir le menu lorsque Loubafritz est déconnecté et vérifier que la statistique est toujours à 1 stp.
Enfin, si ça ne fonctionne toujours pas, j'aurais besoin que tu exécutes la commande `SELECT uuid FROM tigerreports_users WHERE uuid = 3a1ad81d-65ca-4084-8f73-0c1176473d0f` via phpMyAdmin (de ta base de données MySQL) en suivant ce mini tutoriel: https://github.com/MrTigreroux/TigerReports/wiki/Run-a-SQL-query-on-a-MySQL-database#fran%C3%A7ais. Une réponse devrait s'afficher lorsque tu l'exécuteras, il faudrait me la copier ou faire un screenshot.

**Comment by Loubafritz** [comment]
Ma version de Paper: This server is running Paper version git-Paper-68 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: f18dc1e)
Ma version de TigerReports: TigerReports version 4.12.9
Je tape /report Loubafritz
Ca ne marche toujours pas, je fais donc ta manipulation dans PhpMyAdmin.
Voici la réponse:
![image](https://user-images.githubusercontent.com/86154598/124751817-5b18c280-df27-11eb-85e3-9f8a8c7852a1.png)
Voulez-vous que je vous passe les identifiants de mon PhpMyAdmin en MP ?

**Comment by MrTigreroux** [comment]
Merci.
J'aurais maintenant besoin que tu exécutes cette commande stp: `INSERT INTO tigerreports_users (uuid,name) VALUES ('3a1ad81d-65ca-4084-8f73-0c1176473d0f','Loubafritz') ON DUPLICATE KEY UPDATE name=VALUES(name)` et de voir le résultat de l'exécution.
Puis dans une seconde requête, refaire `SELECT uuid FROM tigerreports_users WHERE uuid = '3a1ad81d-65ca-4084-8f73-0c1176473d0f'` avec le résultat stp.

**Comment by Loubafritz** [comment]
Première manip:
![image](https://user-images.githubusercontent.com/86154598/124968953-6c94c400-e026-11eb-94eb-9b643df68ddd.png)

Deuxième manip:
![image](https://user-images.githubusercontent.com/86154598/124969019-80402a80-e026-11eb-8600-de92f98d822d.png)

**Comment by MrTigreroux** [comment]
Merci pour ce deuxième test. Je viens de trouver le temps de faire une mise à jour ([version 4.12.10](https://www.spigotmc.org/resources/tigerreports.25773/update?update=413964)) où je pense que ce problème devrait être corrigé. Si ce n'est pas le cas n'hésite pas à me le signaler. Merci pour ton aide pour essayer de trouver d'où vient le problème.
