### ISSUE TITLE
is it up to date? (Paper 1.16.5-780)

### ISSUE THREAD

**Issue by Klmar** [MrTigreroux/TigerReports#72]
hello i am having issues with installing plugin here  server log:
[latest.log](https://github.com/MrTigreroux/TigerReports/files/6800987/latest.log)

**Comment by MrTigreroux** [comment]
It is a strange error. Try to download again the plugin TigerReports, then stop your server, then put it in your plugins folder and then restart your server. If this error still happens, juste create a new `config.yml` file in the `plugins/TigerReports` folder of your server and copy/paste these default settings in it: https://raw.githubusercontent.com/MrTigreroux/TigerReports/master/TigerReports/src/config.yml

**Comment by Klmar** [comment]
sadly it didnt work when i start my server tiger reports dont create a folder named tigerreports so i tried creating a folder named tigerreports and created a yml file named config then pasted  this  inside of config https://raw.githubusercontent.com/MrTigreroux/TigerReports/master/TigerReports/src/config.yml sadly still now working here server log: 
[latest.log](https://github.com/MrTigreroux/TigerReports/files/6809381/latest.log)

**Comment by MrTigreroux** [comment]
Yes but you need to download again TigerReports.jar from SpigotMC. Have you done it ?

**Comment by Klmar** [comment]
Yes i do it

**Comment by Klmar** [comment]
i guess i am  a dumb or anything like that so can you send me a ready to use folder for 1.16.5 if  it gives error again maybe it will be more helpful

**Comment by MrTigreroux** [comment]
Could you drag and drop your TigerReports.jar file here please ("Attach files by dragging & dropping...") ?

**Comment by Klmar** [comment]
[TigerReports.zip](https://github.com/MrTigreroux/TigerReports/files/6813741/TigerReports.zip)
i have winrar and here is the jar file .

**Comment by MrTigreroux** [comment]
It seems that your system, for a completely unknown reason, replaces `config.yml` file name by `confýg.yml`.
Anyway, I would like that you try to rename the file in TigerReports.jar file by `confýg.yml`. In order to do it, just open TigerReports.jar file with WinRaR and right click on `config.yml` and then click on `Rename` and write `confýg.yml` and enter. Then try to restart your server with this new jar placed in your `plugins` folder.
<br>
![](https://i.imgur.com/AvOBn6P.png)

**Comment by Klmar** [comment]
oh got it there is a problem with my system it didnt work too btw but we will get a server soon so probably if i start the plugin in the vds it will work right?

**Comment by MrTigreroux** [comment]
Let me know if it works on your server. I will try an other way of getting the file name in the next version but I'm not sure that it will work on your system.

**Comment by Klmar** [comment]
it works : i just have to rename config.yml to confıg.yml

**Comment by MrTigreroux** [comment]
Should be fixed in new [version 4.12.10](https://www.spigotmc.org/resources/tigerreports.25773/update?update=413964). Thank you for reporting it.
