### ISSUE TITLE
A Bug Maybe?

### ISSUE THREAD

**Issue by Klmar** [MrTigreroux/TigerReports#73]
Hello its me again i think i found a bug  here is the server log:

[latest.log](https://github.com/MrTigreroux/TigerReports/files/6834960/latest.log)
![Screenshot_103](https://user-images.githubusercontent.com/53684872/126042873-2d38827f-01d8-4684-937a-c4b7befe322f.png)  

Look At The Recevied Reports 

And One More Question i can report my self is this a feature or a bug?

**Comment by Klmar** [comment]
İts  A Weird Error İ tried Plugin İn a diffrent server and it didnt work like that i have really big problems with my pc i guess so plugin work great

**Comment by MrTigreroux** [comment]
Effectively, I think that the method I use to get name of statistics but also name of config files is affected by your system. Will try to get those names in another way in the next version, thank you for reporting the issue.

**Comment by Klmar** [comment]
okay thanks ^^

**Comment by MrTigreroux** [comment]
Should be fixed in new [version 4.12.10](https://www.spigotmc.org/resources/tigerreports.25773/update?update=413964). Thank you for reporting it.
