### ISSUE TITLE
Add _Id_ placeholder to AutoCommands

### ISSUE THREAD

**Issue by piotrskibapl** [MrTigreroux/TigerReports#75]
Hi,

I have a suggestion to add a `_Id_` placeholder to be usable in `AutoCommands` section in the config.
Would be great if it could be implemented.

Thanks!

**Comment by MrTigreroux** [comment]
Hello,
Ok, will add it when I find time, thank you for the suggestion.

**Comment by MrTigreroux** [comment]
It has been added in new [version 4.12.11](https://www.spigotmc.org/resources/tigerreports.25773/update?update=421775). Thank you again for the suggestion, have a good day.
