### ISSUE TITLE
Some messages are not editable 

### ISSUE THREAD

**Issue by MuskPro** [MrTigreroux/TigerReports#79]
I can't edit some messages like:

Process-status-details: "&7Clique para processar."
Delete-details: "&7Clique para excluir esta denúncia."

I save the configuration, but in the menu, the message doesn't change. 

I'm Brazilian, sorry for my bad english.

**Comment by MrTigreroux** [comment]
Hello, just restart your server and they will be updated. Some messages are not updated with a simple reload for performance reasons.

**Comment by MuskPro** [comment]
Thank you very much.
