### ISSUE TITLE
Problem when using report menu and on Offline players

### ISSUE THREAD

**Issue by Korinocho** [MrTigreroux/TigerReports#80]
Hi!
Im having 2 problems:
The first one is that report menu is executing commands that doesnt exist:
![image](https://user-images.githubusercontent.com/21372197/132985572-7be7a520-1fda-4293-a78d-09fe4bddc843.png)
The command "/tigerreports:report" doesn't exist either isnt being registered (i solver this decompiling the plugin and changing this:
![image](https://user-images.githubusercontent.com/21372197/132985663-c7255c76-97b6-4043-af99-9fe80cf34593.png)
in ReasonMenu.class from /tigerreports:report to just /report

The second problem is that (even if i just connected with that account) i cant report offline players.

Im using MySQL (it works fine) and Bungee compatibility

**Comment by MrTigreroux** [comment]
Hello,

The command /tigerreports:report must exist. If it doesn't, that means that another plugin is disturbing it.
For your second problem, what error message do you get when you report an offline player ? Have you disabled [Config: ReportOnline](https://github.com/MrTigreroux/TigerReports/blob/36df7aa7e20cbd02c92b31bf8098e08834d2e2d4/TigerReports/src/config.yml#L24) setting in config.yml file ?

**Comment by Korinocho** [comment]
![image](https://user-images.githubusercontent.com/21372197/133005879-aff3f093-ac1a-420f-9510-a1cd8f2d976d.png)
I havent touched the Reportonline, its by default no.

Solved the first one, PL-Hide-Pro has an option to block all the "/plugin:command" commands by default. Sorry about that :D

**Comment by Korinocho** [comment]
Well
Suddenly the reports works good for offline player. Idk what happened

**Comment by MrTigreroux** [comment]
Ok, good that it now works.
