### ISSUE TITLE
There in "[Director] thiagogebrim" it was supposed to be in RGB a golden color, apparently RGB doesn't work, it would be nice to add RGB support

### ISSUE THREAD

**Issue by thiagogebrimm** [MrTigreroux/TigerReports#84]
![image](https://user-images.githubusercontent.com/75040244/134929249-623d23f8-7d01-4638-866e-75b35a340574.png)

**Comment by MrTigreroux** [comment]
Hello, I assume you use Vault plugin and enabled VaultChat setting in config.yml file of TigerReports plugin. What version of Spigot do you use on your Spigot server (you can see it with `/icanhasbukkit` command), and what version of TigerReports do you use (`/ver TigerReports`) ? What plugin do you use to configure the prefix "[Director]" (with colors), is it compatible with Vault plugin ? What is the exact prefix configured ?

**Comment by thiagogebrimm** [comment]
Spigot version: 
![image](https://user-images.githubusercontent.com/75040244/135004297-a21f4fdb-f507-4e0e-8c6b-c886a02c7e46.png)

TigerReports version:
![image](https://user-images.githubusercontent.com/75040244/135004350-3a68c681-8230-4d88-9daa-c7058721e144.png)

I use luckperms to set the prefix

Prefix are: &#ffcb00[Diretor]

**Comment by MrTigreroux** [comment]
Have you tried to do `/reports reload` or to restart your server ?

**Comment by thiagogebrimm** [comment]
Yes, since I started using the plugin I already had this problem

**Comment by thiagogebrimm** [comment]
In chat it works normally, and on other systems too, only on reports that do not have RGB
![image](https://user-images.githubusercontent.com/75040244/135185114-26bc2ac8-b19e-4c7c-aa8e-60887a3a7a9c.png)

**Comment by MrTigreroux** [comment]
Ok, that is really strange. Could you copy/paste your VaultChat section in config.yml file please ?
Could you try to write some messages in chat, then report yourself, then open the report menu and right click on the data book (top right corner) and check that your prefix is in correct gold color or not in the chat ?
Is your prefix in correct color in staff alerts (when a report is processed, deleted, ...) ?
Was your first screen an alert message received instantly after the report was processed or is it an alert of a report that was processed when you wasn't connected and that you got when connecting to the server ?
