### ISSUE TITLE
Disable possibility to resolve a report if you're the reported player

### ISSUE THREAD

**Issue by piotrskibapl** [MrTigreroux/TigerReports#88]
Hi,

I have a suggestion to disable the possibility to resolve a report if you are the reported player. In case of improper behavior of some staff member, currently he could just remove it or mark it as invalid. There could be a permission that would give the player immunity to this feature - so, for example, moderators could not resolve such reports but admins could.

Thanks! :)

**Comment by MrTigreroux** [comment]
Hello.
Thank you for the suggestion but I'm not really convinced. There is already a specific permission for deleting reports, so if you don't give it to your staff, the report will still be present in archives (and can not automatically be archived). If a staff member isn't allowed to process a report concerning him, then any other staff could do so and the "problem" is still there. In my opinion, TigerReports shouldn't be used for reporting a staff member. You can't put an argumented reason in about 150 characters. I guess that if one staff member is reported, there should have screenshots or videos to give, Minecraft doesn't allow to display them efficiently.
In theory that could be a good feature, but concretely it appears to me to be very overkill and I don't really want to spend time on adding a feature that will probably never be used (if I wanted to report a staff member, using the `/report` command of a server, which obviously alerts staff members, would be the last thing I would do).
