### ISSUE TITLE
reports user command

### ISSUE THREAD

**Issue by ItzRonaldMLG** [MrTigreroux/TigerReports#90]
Hello,
I found the command /reports user <player> while making a help page for staff.
I was wondering what it does because i never used it.
But its having an error xD https://i.imgur.com/wIVAhuh.png
(Of course the player does have joined or is online)

What information does the command give? How many the player did receive and how much true and false reports?

**Comment by MrTigreroux** [comment]
Hello,
That command opens the User menu that displays statistics about the player, but also the current cooldown if there is one, and buttons to see reports where the player is concerned.
Is your Minecraft server allowing crack versions (not premium Minecraft clients) to join ?
Try to restart your server and your problem should be fixed.

**Comment by ItzRonaldMLG** [comment]
The server is offline mode because its on a Bungee Network.
Yes, the restart did fix it for some reason... I didnt change anything.

**Comment by MrTigreroux** [comment]
Ok, nice to know it is fixed. If you encounter any other problem do not hesitate to report it.
