### ISSUE TITLE
Petit problème d'intégration discord

### ISSUE THREAD

**Issue by sayanke** [MrTigreroux/TigerReports#91]
Bonjour ,

J'ai un petit problème avec le plugin , j'ai bien suivi étape par étape le tuto très complet .

Mais petit souci , au niveau de l'intégration sur discord , il m'affiche pas quand un ticket est tombé comme sur les photos 
La seul chose qu'il affiche est ( Le Report #1 a été traité par *** )

Comment avoir les tickets bien mis en place comme , nouveau ticket , en attente etc ...

Merci d'avance 

Sayanke

**Comment by MrTigreroux** [comment]
Bonjour,
Est-ce que vous pourriez me faire des screenshots du problème s'il vous plaît ? Un screenshot in game (sur votre serveur Spigot avec un report qui vient d'être créé) et un screenshot de votre channel Discord où le bot a été configuré.
Vous pouvez aussi essayer de relancer votre serveur Spigot (et non un simple `/reload`).
Peut-être aussi que vous avez une erreur dans les logs/la console de votre serveur Spigot lorsqu'un report est créé, si c'est le cas j'aimerais bien un copier/coller s'il vous plaît.

**Comment by sayanke** [comment]
![problème](https://user-images.githubusercontent.com/44336553/143779487-959b5c9a-7c9f-4d5c-8b63-13ec2c730fb8.jpg)
![2021-11-28_18 41 51](https://user-images.githubusercontent.com/44336553/143779493-e17d5c11-390b-4b60-89a4-23ee90f18e73.png)
![problèmes2](https://user-images.githubusercontent.com/44336553/143779564-463a4dd8-b7bd-433c-94e5-e9935bae1186.jpg)

J'avais pas vue le problème niveau console mais la je sais pas :/

**Comment by MrTigreroux** [comment]
Tu as configuré une URL invalide pour l'option Thumbnail dans ton fichier config.yml dans le dossier plugins/TigerReportsSupports.

**Comment by sayanke** [comment]
super ça fonctionne nickel petite question , le format de l'image c'est comment car l'image ne s'affiche pas ,merci d'avance et merci pour ce plugin

**Comment by MrTigreroux** [comment]
Il faut configurer une adresse Web (URL) d'une image, par exemple au format png. Exemple: `https://cravatar.eu/avatar/_Reported_/64.png` affiche la tête du joueur signalé.
