### ISSUE TITLE
Locale bug

### ISSUE THREAD

**Issue by NineTown** [MrTigreroux/TigerReports#92]
Hello! I use 4.13 version of TigerReports and have a bug. I use own Russian locale. 
The "Staff-punish:" line is always French.
Even I use default Russian, English translation (from spigotmc page), this message always on French.

![2](https://user-images.githubusercontent.com/7281619/143944260-f0420752-0193-4089-a93b-c44cf2099e51.png)
![3](https://user-images.githubusercontent.com/7281619/143944262-28f77cd1-7f1c-4ff1-9aad-55cbd2fe9840.png)

**Comment by NineTown** [comment]
`Messages: # Russian messages by Dreylox. If you are in Minecraft 1.8 or less, encode in ANSI, else encode in UTF-8 / Перевод на русский язык выполнен Dreylox. Если Вы используете Minecraft 1.8 или меньше, используйте кодировку ANSI, если Вы используете Minecraft более высокой версии, используйте кодировку UTF-8.
  Reload: "&c&lРЕПОРТЫ &f&l» &7Конфигурация плагина была перезагружена."
  Report-sent: |
    &c&lРЕПОРТЫ &f&l» &7Вы отправили репорт на игрока &c_Player_&7.
    &8&l- &7Причина: &6_Reason_&7.
    &8
    &8&l[&c&l!&8&l] &7Помните, что ложный репорт - &cнарушение правил&7.
  Alert: |
    &c&lРЕПОРТЫ &f&l» &7Игрок &c_Reporter_ &7отправил репорт на &c_Reported_&7.
    &8&l- &7Причина: &6_Reason_&7.
  Alert-details: "&7Нажмите, чтобы открыть детали &c_Report_&7."
  Teleport-to-current-location: |
    &c&lРЕПОРТЫ &f&l» &7Вы были телепортированы
    &8&l- &7к игроку &c_Player_&7. _ReportButton_
  Teleport-to-old-location: |
    &c&lРЕПОРТЫ &f&l» &7Вы были телепортированы на 
    &8&l- &7местоположение игрока &c_Player_ 
    &8&l- &7во время отправления &d_Report_&7.
    &8&l- _ReportButton_
  Staff-punish: |
    &c&lРЕПОРТЫ &f&l» &7Игрок &c_Player_ &7запретил &c_Reporter_ 
    &8&l- &7отправять жалобы на &6_Time_&7.
  Punished: |
    &c&lРЕПОРТЫ &f&l» &7Вам запретили отправлять репорты на игроков. 
    &8&l- &7Вы сможете отправить репорт через: &c_Time_&7.
  Staff-stop-cooldown: "&c&lРЕПОРТЫ &f&l» &7Игрок &c_Player_ &7отменил задержку на отправление репортов для &6_Target_&7."
  Cooldown-stopped: |
    &c&lРЕПОРТЫ &f&l» &7Задержка до следующего репорта была отменена.
    &8&l- &7Теперь Вы снова можете использовать &c/report&7.
  Staff-process: "&c&lРЕПОРТЫ &f&l» &7Игрок &c_Player_ &7установил статус &d_Report_ &7на _Appreciation_&7."
  Staff-process-auto: "&c&lРЕПОРТЫ &f&l» &7Игрок &c_Player_ &7установил статус &d_Report_ &7на _Appreciation_ &7и отправил его в архив."
  Staff-process-punish: "&c&lРЕПОРТЫ &f&l» &7Игрок &c_Player_ &7установил статус &d_Report_ &2Верный&7, и &7наказал &c_Reported_ &7за &6_Punishment_&7."
  Staff-process-punish-auto: "&c&lРЕПОРТЫ &f&l» &7Игрок &c_Player_ &7установил статус &d_Report_ &2Верный&7, наказал &c_Reported_ &7за &6_Punishment_ &7и отправил репорт в архив."
  Staff-archive: "&c&lРЕПОРТЫ &f&l» &7Игрок &c_Player_ &7отправил &d_Report_&7 в архив."
  Staff-archiveall: "&c&lРЕПОРТЫ &f&l» &7Игрок &c_Player_ &7отправил в архив все рассмотренные репорты."
  Staff-deleteall-archived: "&c&lРЕПОРТЫ &f&l» &7Игрок &c_Player_ &7удалил все репорты из архива."
  Staff-deleteall-unarchived: "&c&lРЕПОРТЫ &f&l» &7Игрок &c_Player_ &7удалил все репорты вне архива."
  Staff-delete-archive: "&c&lРЕПОРТЫ &f&l» &7Игрок &c_Player_ &7удалил из архива &d_Report_&7."
  Staff-delete: "&c&lРЕПОРТЫ &f&l» &7Игрок &c_Player_ &7удалил &d_Report_&7."
  Staff-restore: "&c&lРЕПОРТЫ &f&l» &7Игрок &c_Player_ &7восстановил &d_Report_&7."
  Staff-max-reports-reached: "&c&lРЕПОРТЫ &f&l» &7Максимальное количество репортов &8(&c_Amount_&8) &7было превышено. Новые репорты не сохраняются."
  Staff-notifications: "&c&lРЕПОРТЫ &f&l» &7Уведомления о репортах были _State_&7."
  Comment-notification: |
    &c&lРЕПОРТЫ &f&l» &7Персонал ответил на Ваш репорт на &c_Reported_ &8| &c_Time_ &7назад: 
    &8&l- &6_Message_&7.
  Report-notification: "&c&lРЕПОРТЫ &f&l» &7Персонал рассмотрел Ваш &d_Report_ &7как _Appreciation_ &6_Time_ &7назад."
  Reports-notification: |
    &c&lРЕПОРТЫ &f&l» &7На данный момент в базе
    &8&l- &c_Waiting_&7.
    &8&l- &c/reports &7для просмотра всех репортов.
  Report-button: "&8(&7Открыть &8» &7_Report_&8)"
  Report-chat-details: "&8&m---------------------------------------------------//&r                              _Report_//&8&m---------------------------------------------------//&8&l| &7Статус: _Status_ &8| &7Дата: &e_Date_//&8&l| &7Автор(ы): &2_Reporters_//&8&l| &7Нарушитель: &c_Reported_//&8&l| &7Причина: &e_Reason_// //_ReportButton_//&8&m---------------------------------------------------//"
  Report-chat-data: "&8&m---------------------------------------------------//&r                        &7_Report_ &8» &7Информация//&8&m---------------------------------------------------//&8&l| &7Нарушитель: &c_Reported_//_DefaultData_//_AdvancedData_//_ReportButton_//&8&m---------------------------------------------------"
  Report-messages-history: "&8&m---------------------------------------------------//&r                  &7_Report_ &8» &7История сообщений//&8&m---------------------------------------------------//_Messages_// //_ReportButton_//&8&m---------------------------------------------------"
  Report-message-format: "//&8(&c_Date_&8) &c_Player_&7: &7_Message_"
  Edit-comment: "&c&lРЕПОРТЫ &f&l» &7Пожалуйста, напишите Ваш комментарий в чат для &c_Report_&7. _CancelButton_"
  Cancel-button: "&7[&cО&cт&cм&cе&cн&cа&7]"
  Cancel-button-details: "&8&l| &cНажмите ЛКМ&7, чтобы отменить свой комментарий//&8&l| &7для &c_Report_&7."          
  Cancel-comment: "&c&lРЕПОРТЫ &f&l» &7Вы отменили комментарий для _Report_&7. _ReportButton_"
  Report-details: "_Report_// //&7Статус: _Status_//&7Дата: &e_Date_// //&7Автор репорта: &2_Reporters_//&7Нарушитель: &c_Reported_//&7Причина: &6_Reason_"
  Help-commands: ""
ErrorMessages:
  Invalid-syntax-report: |
    &c&lРЕПОРТЫ &f&l» &7Пожалуйста, детализируйте Вашу команду как: 
    &8&l- &c/report &8<&cник игрока&8» (&cпричина&8)&7.
  Invalid-syntax-reports: "&c&lРЕПОРТЫ &f&l» &7Пожалуйста, детализируйте вашу команду."
  Permission-command: "&c&lРЕПОРТЫ &f&l» &7У Вас нет прав на выполнение этой команды."
  Permission-report: "&c&lРЕПОРТЫ &f&l» &7Вы не можете отправить репорт на игрока &c_Player_&7."
  Permission-access-details: "&c&lРЕПОРТЫ &f&l» &7Вы не можете отправить репорт на игрока &c_Player_&7."
  Player-only: "&c&lРЕПОРТЫ &f&l» &7Эта команда недоступна в игре."
  Cooldown: "&c&lРЕПОРТЫ &f&l» &7Пожалуйста, подождите &c_Time_&7, прежде чем отправить репорт."
  Report-oneself: "&c&lРЕПОРТЫ &f&l» &7Вы не можете отправить репорт на самого себя."
  Reported-offline: |
    &c&lРЕПОРТЫ &f&l» &7Вы не можете отправить репорт на игрока, 
    &8&l- &7который не в сети &8(&c_Player_&8)&7.
  Player-already-reported: |
    &c&lРЕПОРТЫ &f&l» &7На игрока &c_Player_ &7уже была отправлен репорт.
    &8&l- &7Пожалуйста, подождите &6_Time_&7.
  Player-already-reported-by-you: |
    &c&lРЕПОРТЫ &f&l» &7Вы уже отправили репорт на &с_Player_. 
    &8&l- &7Причина: &6_Reason_&7.
  Too-short-reason: "&c&lРЕПОРТЫ &f&l» &7Причина репорта слишком короткая."
  Location-unknown: "&c&lРЕПОРТЫ &f&l» &7Местоположение &c_Player_ &7во время репорта не найдено."
  Invalid-report-id: "&c&lРЕПОРТЫ &f&l» &7Вы указали неверный ID репорта &8(&d_Id_&8)&7."
  Invalid-report: "&c&lРЕПОРТЫ &f&l» &7Репорт недействителен."
  Invalid-player: "&c&lРЕПОРТЫ &f&l» &7Игрок &c_Player_ &7не заходил на этот сервер."
  Player-offline: "&c&lРЕПОРТЫ &f&l» &7Игрок &c_Player_ &7сейчас не в сети."
Menus:
  Reason-title: "&8Репорт на &8_Target_"
  Reasons: "&8&l▶ &7Причины репротп"
  Reason: "&8&l▶ &7Причина: &c_Reason_"
  Reason-details: "//_Lore_// //&8&l| &cНажмите&7, чтобы отправить//&8&l| &7репорт на &c_Player_//&8&l| &7по причине:// //&8&l| &6_Reason_&7"
  Report: "&8&l▶ &7_Report_"
  Report-details: "//&8&l| &7Статус: _Status_//&8&l| &7Дата: &c_Date_// //&8&l| &7Автор репорта: &c_Reporters_//&8&l| &7Нарушитель: &c_Reported_//&8&l| &7Причина: &e_Reason_ &r_Actions_"
  Report-show-action: "// //&8&l| &cНажмите &7для деталей."
  Report-archive-action: "//&8&l| &cКолёсико мыши&7, чтобы//&8&l| &7добавить репорт в архив."
  Report-delete-action: "//&8&l| &cНажмите Q&7, для удаления."
  Reports-title: "&8Репорты &0» &8Страница _Page_"
  Reports: "&8&l▶ &7Репорты"
  Reports-details: "//&8&l| &cНажмите, &7чтобы//&8&l| &7увидеть все репорты."
  Report-title: "&8Репорты &0» &8_Report_"
  Report-chat-action: "// //&8&l| &cНажмите ЛКМ&7, чтобы//&8&l| &7написать в чат."
  Reporter: "&8&l▶ &7Автор репорта: &c_Player_"
  Reported: "&8&l▶ &7Нарушитель: &e_Player_"
  Player-details: "//&8&l| &7Репортов отправлено: &2_Reports_//&8&l| &7Репортов принято: &c_Reportedtimes_// //&8&l| &7Сервер во время репорта://&8&l| &d_Server_//_Teleportation_"
  Stacked-report-reporters: "&7Авторы"
  Stacked-report-reporters-details: "//&7Перый автор://_First_//&7Другие авторы: _Others_// //&7Сервер во время репорта: &d_Server_//_Teleportation_"
  Teleport-to-current-position: "//&8&l| &cНажмите ЛКМ&7, чтобы//&8&l| &7телепортироваться//&8&l| &7на текущее место//&8&l| &6_Player_&7.//"
  Can-not-teleport-to-current-position: "//&8&l| &cНажмите ЛКМ&7, чтобы//&8&l| &7телепортироваться//&8&l| &7на текущее место//&8&l| &6_Player_&7.//"
  Teleport-to-old-position: "//&8&l| &cНажмите ЛКМ&7, чтобы//&8&l| &7телепортироваться//&8&l| &7на старое место//&8&l| &6_Player_&7.//"
  Can-not-teleport-to-old-position: "//&8&l| &cНажмите ЛКМ&7, чтобы//&8&l| &7телепортироваться//&8&l| &7на старое место//&8&l| &6_Player_&7.//"
  Punish-abuse: "&8&l▶ &4Ложный репорт"
  Punish-abuse-details: "//&8&l| &cНажмите, &7чтобы наказать //&8&l| &7автора репорта&7."
  Change-status: "&8&l▶ &7Установить статус: &r_Status_"
  Change-status-details: "//&8&l| &cНажмите, &7чтобы установить//&8&l| &7статус репорта на: &r_Status_&7."
  Process-status: "&8&l▶ &2Завершить рассмотрение репорта"
  Process-status-details: "//&8&l| &cНажмите, &7чтобы завершить//&8&l| &7рассмотрение репорта."
  Archive: "&8&l▶ &7В архив репортов"
  Archive-details: "//&8&l| &cНажмите, &7чтобы отправить//&8&l| &7репорт в архив."
  Data: "&8&l▶ &7Дополнительная информация"
  Data-details: "//&8&l| &7Нарушитель: &c_Reported_//_DefaultData_//_AdvancedData_//&8&l| &cЛКМ&7, чтобы открыть чат.//&8&l| &cПКМ&7, чтобы открыть//&8&l| &7историю чата."
  Default-data: "&8&l| &7Игровой режим: _Gamemode_&7//&8&l| &7На земле: _OnGround_&7, &7присел: _Sneak_//&8&l| &7Скорость: _Sprint_&7, &7Эффекты: _Effects_//&8&l| &7Здоровье: &c_Health_&7, &7сытость: &6_Food_//"
  Player-was-offline: "&8&l| &7Игрок был оффлайн во время репорта."
  Effect: "// &7- &b_Type_ _Amplifier_ &7(&8_Duration_ seconds&7)"
  Advanced-data-reported: "&8&l| &7UUID: &8_UUID_//&8&l| &7IP: &8_IP_//"
  Advanced-data-reporter: "//&8&l| &7Автор репорта: &e_Player_//&8&l| &7UUID: &8_UUID_//&8&l| &7IP: &8_IP_//"
  Comments: "&8&l▶ &7Комментарии к репорту"
  Comments-details: "//&8&l| &cНажмите, &7чтобы открыть//&8&l| &7комментарии репорта."
  Delete: "&8&l▶ &cУдалить репорт"
  Delete-details: "//&8&l| &cНажмите, &7чтобы безвозвратно//&8&l| &7удалить репорт."
  Confirm-delete-title: "&8Удаление &0» &8_Report_"
  Confirm-delete: "&8&l▶ &2Подтвердить удаление"
  Confirm-delete-details: "//&8&l| &cНажмите, &7чтобы//&8&l| &7удалить _Report_&7."
  Cancel-delete: "&8&l▶ &cОтменить удаление"
  Cancel-delete-details: "//&8&l| &cНажмите, &7чтобы//&8&l| &7отменить удаление."
  Confirm-archive-title: "&8Архив &0» &8_Report_"
  Confirm-archive: "&8&l▶ &2Подтвердить добавление в архив"
  Confirm-archive-details: "//&8&l| &cНажмите&7, чтобы отправить//&8&l| &7репорт &c_Report_ &7в архив&7."
  Cancel-archive: "&8&l▶ &cОтменить добавление в архив"
  Cancel-archive-details: "//&8&l| &cНажмите&7, чтобы отменить//&8&l| &7отправление репорта &c_Report_ &7в архив&7."
  Process-title: "&8Завершение &0» &8_Report_"
  Process: "&8&l▶ &7Завершить как: _Appreciation_"
  Process-details: "//&8&l| &cНажмите&7, чтобы завершить//&8&l| &7репорт как: _Appreciation_&7."
  Cancel-process: "&8&l▶ &cОтменить завершение"
  Cancel-process-details: "//&8&l| &cНажмите&7, чтобы отменить//&8&l| &7завершение."
  Punish-title: "&8Наказания &0» &c_Reported_"
  Punishments: "&8&l▶ &cНаказания"
  No-punishment: "&8&l▶ &2Не наказывать"
  No-punishment-details: "//&8&l| &cНажмите&7, чтобы завершить репорт//&8&l| &7как &2Верно &7без наказания нарушителя//&8&l| &c_Reported_&7."
  Punishment: "&8&l▶ &7Наказать за: &e_Punishment_"
  Punishment-details: "//_Lore_// //&8&l| &cНажмите&7, чтобы наказать игрока//&8&l| &c_Reported_ &7по причине: &e_Punishment_&7."
  Comments-title: "&8Комментарии &0» &8_Report_"
  Comment: "&8&l▶ &7Комментарий &d#_Id_"
  Comment-details: "//&8&l| &7Статус: _Status_//&8&l| &7Автор: &6_Author_//&8&l| &7Дата: &c_Date_//&8&l| &7Сообщение: &d_Message_//_Actions_"
  Comment-add-message-action: "//&8&l| &cНажмите ЛКМ&7, чтобы//&8&l| &7добавить сообщение."
  Comment-send-action: "//&8&l| &cНажмите ПКМ&7, чтобы//&8&l| &7отправить репорт."
  Comment-cancel-send-action: "//&8&l| &cНажмите ПКМ&7, чтобы отменить//&8&l| &7отправку коментария автору репорта."
  Comment-delete-action: "//&8&l| &cНажмите Q&7, для удаления."
  Write-comment: "&8&l▶ &7Напишите комментарий"
  Write-comment-details: "//&8&l| &cНажмите, &7чтобы добавить//&8&l| &7новый комментарий к//&8&l| &7репорту."
  User-title: "&8Игрок &0» &e_Target_"
  User: "&8&l▶ &7Игрок: &c_Target_"
  User-details: "//&8&l| &cНажмите&7, чтобы показать статистику//&8&l| &7игрока &c_Target_&7."
  User-statistic: "&8&l▶ &7Игрок &c_Statistic_&7: &e_Amount_"
  User-statistic-details: "&8&l| &cНажмите ЛКМ&7, чтобы увеличить на один.//&8&l| &cНажмите ПКМ&7, чтобы уменьшить на один."
  Cooldown-status: "&8&l▶ &7Задержка на отправление жалоб: &c_Time_"
  Cooldown-status-details: "//&8&l| &cНажмите&7, чтобы отменить задержку//&8&l| &7игрока &c_Player_&7."
  User-reports: "&8&l▶ &7Репорты от игрока &c_Target_"
  User-reports-details: "//&8&l| &cНажмите&7, чтобы показать активные//&8&l| &7репорты от игрока &c_Target_&7."
  User-reports-title: "&8Репорты &0» &8_Target_ &0» &8Стр _Page_"
  User-archived-reports: "&8&l▶ &7Архивные репорты от игрока &c_Target_"
  User-archived-reports-details: "//&8&l| &cНажмите&7, чтобы показать архивные//&8&l| &7репорты от игрока &c_Target_&7."
  User-archived-reports-title: "&8Архивы &0» &8_Target_ &0» &8Стр _Page_"
  User-against-reports: "&8&l▶ &7Активные репорты против &c_Target_"
  User-against-reports-details: "//&8&l| &cНажмите&7, чтобы открыть активные//&8&l| &7репорты против &c_Target_&7."
  User-against-reports-title: "&8Репорты &0» &8_Target_ &0» &8Стр _Page_"
  User-against-archived-reports: "&8&l▶ &7Архивные репорты против &c_Target_"
  User-against-archived-reports-details: "//&8&l| &cНажмите&7, чтобы открыть архивные//&8&l| &7репорты против &c_Target_&7."
  User-against-archived-reports-title: "&8Архивы &0» &8_Target_ &0» &8Стр _Page_"
  Archived-reports: "&8&l▶ &7Архив репортов"
  Archived-reports-details: "//&8&l| &cНажмите, &7чтобы открыть//&8&l| &7архив репортов."
  Archived-reports-title: "&8Архив &0» &8Страница _Page_"
  Report-restore-action: "// //&8&l| &cНажмите&7, чтобы восстановить."
  Switch-to-previous-page: "&c&l< &7Предыдущая страница"
  Switch-to-next-page: "&7Следующая страница &c&l»"
  Close: "&8&l▶ &cЗакрыть"
Words:
  Report-name: "Репорт &d#_Id_"
  Reported-name: "&c_Player_"
  Reporter-name: "&6_Player_"
  Reporters-names: "//&7- &e_Player_"
  Online-suffix: " &8(&2онлайн&8)"
  Offline-suffix: " &8(&cоффлайн&8)"
  Not-found-male: "&cНе найдено"
  Not-found-female: "&cНе найдено"
  Activated: "&2включено"
  Disabled: "&cвыключено"
  None-male: "&cНет"
  None-female: "&cНет"
  Second: "сек"
  Seconds: "сек"
  Minute: "мин"
  Minutes: "мин"
  Hour: "ч"
  Hours: "ч"
  Day: "д"
  Days: "дн"
  Week: "нед"
  Weeks: "нед"
  Month: "мес"
  Months: "мес"
  Year: "г"
  Years: "г"
  Waiting: "&2Ожидание"
  In-progress: "&6Рассмотрение"
  In-progress-detailed: "&6Рассмотрение &8(&c_Name_&8)"
  Important: "&cВажно"
  Done: "&2Завершено &7_Name_"
  Done-suffix:
    True-appreciation: " &8(&2Верно&8)//&8&l| &7Наказание применено: &r_Punishment_"
    Other-appreciation: " &8(_Appreciation_&8)"
  Appreciation: "&7Завершено как _Appreciation_"
  True-appreciation: "&2Верно"
  Uncertain-appreciation: "&6Неопределено"
  False-appreciation: "&cЛожно"
  Reports-statistic: "Репортов отправленно"
  Reported-times-statistic: "Репортов принято"
  Processed-reports-statistic: "Завершенных репортов"
  Yes-state: "&2да"
  No-state: "&cнет"
  Survival: "&6Выживание"
  Creative: "&bТворческий"
  Adventure: "&5Преключенчиский"
  Spectator: "&7Наблюдатель"
  Private: "&4Приватный"
  Sent: "&6Отправлено"
  Read: "&2Прочитано _Date_"
  Report-type: "&6_Amount_ &7репорт со статусом: _Type_"
  Reports-type: "&6_Amount_ &7репорта(-ов) со статусом: _Type_"`

**Comment by NineTown** [comment]
https://pastebin.com/sDYvLvjH - my own locale config

**Comment by MrTigreroux** [comment]
Hello.
Because you use "|" feature in your file, you can't just use the online updater tool I made ([here](http://mrtigreroux.000webhostapp.com/plugins/tigerreports.php)). However, it can help you to see new messages.
You can also compare your file with [this file](https://github.com/MrTigreroux/TigerReports/blob/master/TigerReports/messages/english.yml).
In your case, the message you circled is now configured by [Messages: Staff-process-abusive](https://github.com/MrTigreroux/TigerReports/blob/0764ed995f8750cad10f9f7f332c4def4de33ba0/TigerReports/messages/english.yml#L14) in messages.yml.
